/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model;


import fr.eaudeparis.syncremocra.db.model.tables.Erreur;
import fr.eaudeparis.syncremocra.db.model.tables.Message;
import fr.eaudeparis.syncremocra.db.model.tables.MotifIndispoActif;
import fr.eaudeparis.syncremocra.db.model.tables.Parametres;
import fr.eaudeparis.syncremocra.db.model.tables.PullHydrant;
import fr.eaudeparis.syncremocra.db.model.tables.PullHydrantAnomalies;
import fr.eaudeparis.syncremocra.db.model.tables.PullHydrantVisite;
import fr.eaudeparis.syncremocra.db.model.tables.PullMessage;
import fr.eaudeparis.syncremocra.db.model.tables.ReferentielAnomalies;
import fr.eaudeparis.syncremocra.db.model.tables.ReferentielHydrantDiametres;
import fr.eaudeparis.syncremocra.db.model.tables.ReferentielMarquesModeles;
import fr.eaudeparis.syncremocra.db.model.tables.TracabiliteIndispo;
import fr.eaudeparis.syncremocra.db.model.tables.TracabilitePei;
import fr.eaudeparis.syncremocra.db.model.tables.TypeErreur;
import fr.eaudeparis.syncremocra.db.model.tables.VueErreurToNotify;
import fr.eaudeparis.syncremocra.db.model.tables.VueErreursEdp;
import fr.eaudeparis.syncremocra.db.model.tables.VuePeiEdpRemocra;
import fr.eaudeparis.syncremocra.db.model.tables.VuePeiMotifIndispoEdpRemocra;
import fr.eaudeparis.syncremocra.db.model.tables.VueVisite;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Edp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>edp</code>
     */
    public static final Edp EDP = new Edp();

    /**
     * Erreur rencontrée lors du processus global de synchronisation entre REMOCRA et EDP et pouvant donner lieu à notification
     */
    public final Erreur ERREUR = Erreur.ERREUR;

    /**
     * The table <code>edp.message</code>.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>edp.motif_indispo_actif</code>.
     */
    public final MotifIndispoActif MOTIF_INDISPO_ACTIF = MotifIndispoActif.MOTIF_INDISPO_ACTIF;

    /**
     * The table <code>edp.parametres</code>.
     */
    public final Parametres PARAMETRES = Parametres.PARAMETRES;

    /**
     * The table <code>edp.pull_hydrant</code>.
     */
    public final PullHydrant PULL_HYDRANT = PullHydrant.PULL_HYDRANT;

    /**
     * The table <code>edp.pull_hydrant_anomalies</code>.
     */
    public final PullHydrantAnomalies PULL_HYDRANT_ANOMALIES = PullHydrantAnomalies.PULL_HYDRANT_ANOMALIES;

    /**
     * The table <code>edp.pull_hydrant_visite</code>.
     */
    public final PullHydrantVisite PULL_HYDRANT_VISITE = PullHydrantVisite.PULL_HYDRANT_VISITE;

    /**
     * The table <code>edp.pull_message</code>.
     */
    public final PullMessage PULL_MESSAGE = PullMessage.PULL_MESSAGE;

    /**
     * The table <code>edp.referentiel_anomalies</code>.
     */
    public final ReferentielAnomalies REFERENTIEL_ANOMALIES = ReferentielAnomalies.REFERENTIEL_ANOMALIES;

    /**
     * The table <code>edp.referentiel_hydrant_diametres</code>.
     */
    public final ReferentielHydrantDiametres REFERENTIEL_HYDRANT_DIAMETRES = ReferentielHydrantDiametres.REFERENTIEL_HYDRANT_DIAMETRES;

    /**
     * The table <code>edp.referentiel_marques_modeles</code>.
     */
    public final ReferentielMarquesModeles REFERENTIEL_MARQUES_MODELES = ReferentielMarquesModeles.REFERENTIEL_MARQUES_MODELES;

    /**
     * The table <code>edp.tracabilite_indispo</code>.
     */
    public final TracabiliteIndispo TRACABILITE_INDISPO = TracabiliteIndispo.TRACABILITE_INDISPO;

    /**
     * The table <code>edp.tracabilite_pei</code>.
     */
    public final TracabilitePei TRACABILITE_PEI = TracabilitePei.TRACABILITE_PEI;

    /**
     * Typologie des erreurs pouvant être rencontrées lors du processus global de synchronisation entre REMOCRA et EDP
     */
    public final TypeErreur TYPE_ERREUR = TypeErreur.TYPE_ERREUR;

    /**
     * The table <code>edp.vue_erreur_to_notify</code>.
     */
    public final VueErreurToNotify VUE_ERREUR_TO_NOTIFY = VueErreurToNotify.VUE_ERREUR_TO_NOTIFY;

    /**
     * The table <code>edp.vue_erreurs_edp</code>.
     */
    public final VueErreursEdp VUE_ERREURS_EDP = VueErreursEdp.VUE_ERREURS_EDP;

    /**
     * The table <code>edp.vue_pei_edp_remocra</code>.
     */
    public final VuePeiEdpRemocra VUE_PEI_EDP_REMOCRA = VuePeiEdpRemocra.VUE_PEI_EDP_REMOCRA;

    /**
     * The table <code>edp.vue_pei_motif_indispo_edp_remocra</code>.
     */
    public final VuePeiMotifIndispoEdpRemocra VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA = VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA;

    /**
     * The table <code>edp.vue_visite</code>.
     */
    public final VueVisite VUE_VISITE = VueVisite.VUE_VISITE;

    /**
     * No further instances allowed
     */
    private Edp() {
        super("edp", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ERREUR_ID_SEQ,
            Sequences.MESSAGE_ID_SEQ,
            Sequences.PULL_HYDRANT_ANOMALIES_ID_SEQ,
            Sequences.PULL_HYDRANT_ID_SEQ,
            Sequences.PULL_HYDRANT_VISITE_ID_SEQ,
            Sequences.PULL_MESSAGE_ID_SEQ,
            Sequences.TRACABILITE_INDISPO_ID_SEQ,
            Sequences.TRACABILITE_PEI_ID_SEQ,
            Sequences.TYPE_ERREUR_ID_SEQ,
            Sequences.VUE_PEI_EDP_REMOCRA_GID_EDP_SEQ,
            Sequences.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA_GID_EDP_SEQ,
            Sequences.VUE_VISITE_GID_EDP_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Erreur.ERREUR,
            Message.MESSAGE,
            MotifIndispoActif.MOTIF_INDISPO_ACTIF,
            Parametres.PARAMETRES,
            PullHydrant.PULL_HYDRANT,
            PullHydrantAnomalies.PULL_HYDRANT_ANOMALIES,
            PullHydrantVisite.PULL_HYDRANT_VISITE,
            PullMessage.PULL_MESSAGE,
            ReferentielAnomalies.REFERENTIEL_ANOMALIES,
            ReferentielHydrantDiametres.REFERENTIEL_HYDRANT_DIAMETRES,
            ReferentielMarquesModeles.REFERENTIEL_MARQUES_MODELES,
            TracabiliteIndispo.TRACABILITE_INDISPO,
            TracabilitePei.TRACABILITE_PEI,
            TypeErreur.TYPE_ERREUR,
            VueErreurToNotify.VUE_ERREUR_TO_NOTIFY,
            VueErreursEdp.VUE_ERREURS_EDP,
            VuePeiEdpRemocra.VUE_PEI_EDP_REMOCRA,
            VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA,
            VueVisite.VUE_VISITE);
    }
}
