/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model;


import fr.eaudeparis.syncremocra.db.model.routines.Changedatacapture;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in edp.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>edp.changedatacapture</code>
     */
    public static Integer changedatacapture(
          Configuration configuration
    ) {
        Changedatacapture f = new Changedatacapture();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>edp.changedatacapture</code> as a field.
     */
    public static Field<Integer> changedatacapture() {
        Changedatacapture f = new Changedatacapture();

        return f.asField();
    }
}
