/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables;


import fr.eaudeparis.syncremocra.db.model.Edp;
import fr.eaudeparis.syncremocra.db.model.Keys;
import fr.eaudeparis.syncremocra.db.model.tables.records.ReferentielMarquesModelesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferentielMarquesModeles extends TableImpl<ReferentielMarquesModelesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>edp.referentiel_marques_modeles</code>
     */
    public static final ReferentielMarquesModeles REFERENTIEL_MARQUES_MODELES = new ReferentielMarquesModeles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReferentielMarquesModelesRecord> getRecordType() {
        return ReferentielMarquesModelesRecord.class;
    }

    /**
     * The column <code>edp.referentiel_marques_modeles.code_modele_edp</code>.
     */
    public final TableField<ReferentielMarquesModelesRecord, String> CODE_MODELE_EDP = createField(DSL.name("code_modele_edp"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>edp.referentiel_marques_modeles.code_marque_remocra</code>.
     */
    public final TableField<ReferentielMarquesModelesRecord, String> CODE_MARQUE_REMOCRA = createField(DSL.name("code_marque_remocra"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>edp.referentiel_marques_modeles.code_modele_remocra</code>.
     */
    public final TableField<ReferentielMarquesModelesRecord, String> CODE_MODELE_REMOCRA = createField(DSL.name("code_modele_remocra"), SQLDataType.VARCHAR.nullable(false), this, "");

    private ReferentielMarquesModeles(Name alias, Table<ReferentielMarquesModelesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReferentielMarquesModeles(Name alias, Table<ReferentielMarquesModelesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>edp.referentiel_marques_modeles</code> table reference
     */
    public ReferentielMarquesModeles(String alias) {
        this(DSL.name(alias), REFERENTIEL_MARQUES_MODELES);
    }

    /**
     * Create an aliased <code>edp.referentiel_marques_modeles</code> table reference
     */
    public ReferentielMarquesModeles(Name alias) {
        this(alias, REFERENTIEL_MARQUES_MODELES);
    }

    /**
     * Create a <code>edp.referentiel_marques_modeles</code> table reference
     */
    public ReferentielMarquesModeles() {
        this(DSL.name("referentiel_marques_modeles"), null);
    }

    public <O extends Record> ReferentielMarquesModeles(Table<O> child, ForeignKey<O, ReferentielMarquesModelesRecord> key) {
        super(child, key, REFERENTIEL_MARQUES_MODELES);
    }

    @Override
    public Schema getSchema() {
        return Edp.EDP;
    }

    @Override
    public UniqueKey<ReferentielMarquesModelesRecord> getPrimaryKey() {
        return Keys.REFERENTIEL_MARQUES_MODELES_PKEY;
    }

    @Override
    public List<UniqueKey<ReferentielMarquesModelesRecord>> getKeys() {
        return Arrays.<UniqueKey<ReferentielMarquesModelesRecord>>asList(Keys.REFERENTIEL_MARQUES_MODELES_PKEY);
    }

    @Override
    public ReferentielMarquesModeles as(String alias) {
        return new ReferentielMarquesModeles(DSL.name(alias), this);
    }

    @Override
    public ReferentielMarquesModeles as(Name alias) {
        return new ReferentielMarquesModeles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReferentielMarquesModeles rename(String name) {
        return new ReferentielMarquesModeles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReferentielMarquesModeles rename(Name name) {
        return new ReferentielMarquesModeles(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
