/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables;

import fr.eaudeparis.syncremocra.db.model.Edp;
import fr.eaudeparis.syncremocra.db.model.Keys;
import fr.eaudeparis.syncremocra.db.model.tables.records.ReferentielHydrantDiametresRecord;
import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReferentielHydrantDiametres extends TableImpl<ReferentielHydrantDiametresRecord> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>edp.referentiel_hydrant_diametres</code> */
  public static final ReferentielHydrantDiametres REFERENTIEL_HYDRANT_DIAMETRES =
      new ReferentielHydrantDiametres();

  /** The class holding records for this type */
  @Override
  public Class<ReferentielHydrantDiametresRecord> getRecordType() {
    return ReferentielHydrantDiametresRecord.class;
  }

  /** The column <code>edp.referentiel_hydrant_diametres.code_bspp</code>. */
  public final TableField<ReferentielHydrantDiametresRecord, String> CODE_BSPP =
      createField(DSL.name("code_bspp"), SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>edp.referentiel_hydrant_diametres.code_edp</code>. */
  public final TableField<ReferentielHydrantDiametresRecord, String> CODE_EDP =
      createField(DSL.name("code_edp"), SQLDataType.VARCHAR.nullable(false), this, "");

  private ReferentielHydrantDiametres(
      Name alias, Table<ReferentielHydrantDiametresRecord> aliased) {
    this(alias, aliased, null);
  }

  private ReferentielHydrantDiametres(
      Name alias, Table<ReferentielHydrantDiametresRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /** Create an aliased <code>edp.referentiel_hydrant_diametres</code> table reference */
  public ReferentielHydrantDiametres(String alias) {
    this(DSL.name(alias), REFERENTIEL_HYDRANT_DIAMETRES);
  }

  /** Create an aliased <code>edp.referentiel_hydrant_diametres</code> table reference */
  public ReferentielHydrantDiametres(Name alias) {
    this(alias, REFERENTIEL_HYDRANT_DIAMETRES);
  }

  /** Create a <code>edp.referentiel_hydrant_diametres</code> table reference */
  public ReferentielHydrantDiametres() {
    this(DSL.name("referentiel_hydrant_diametres"), null);
  }

  public <O extends Record> ReferentielHydrantDiametres(
      Table<O> child, ForeignKey<O, ReferentielHydrantDiametresRecord> key) {
    super(child, key, REFERENTIEL_HYDRANT_DIAMETRES);
  }

  @Override
  public Schema getSchema() {
    return Edp.EDP;
  }

  @Override
  public UniqueKey<ReferentielHydrantDiametresRecord> getPrimaryKey() {
    return Keys.REFERENTIEL_HYDRANT_DIAMETRES_PKEY;
  }

  @Override
  public List<UniqueKey<ReferentielHydrantDiametresRecord>> getKeys() {
    return Arrays.<UniqueKey<ReferentielHydrantDiametresRecord>>asList(
        Keys.REFERENTIEL_HYDRANT_DIAMETRES_PKEY);
  }

  @Override
  public ReferentielHydrantDiametres as(String alias) {
    return new ReferentielHydrantDiametres(DSL.name(alias), this);
  }

  @Override
  public ReferentielHydrantDiametres as(Name alias) {
    return new ReferentielHydrantDiametres(alias, this);
  }

  /** Rename this table */
  @Override
  public ReferentielHydrantDiametres rename(String name) {
    return new ReferentielHydrantDiametres(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public ReferentielHydrantDiametres rename(Name name) {
    return new ReferentielHydrantDiametres(name, null);
  }

  // -------------------------------------------------------------------------
  // Row2 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row2<String, String> fieldsRow() {
    return (Row2) super.fieldsRow();
  }
}
