/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables;


import fr.eaudeparis.syncremocra.db.binding.PointBinding;
import fr.eaudeparis.syncremocra.db.model.Edp;
import fr.eaudeparis.syncremocra.db.model.tables.records.VuePeiEdpRemocraRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.locationtech.jts.geom.Point;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VuePeiEdpRemocra extends TableImpl<VuePeiEdpRemocraRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>edp.vue_pei_edp_remocra</code>
     */
    public static final VuePeiEdpRemocra VUE_PEI_EDP_REMOCRA = new VuePeiEdpRemocra();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VuePeiEdpRemocraRecord> getRecordType() {
        return VuePeiEdpRemocraRecord.class;
    }

    /**
     * The column <code>edp.vue_pei_edp_remocra.gid_edp</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, Integer> GID_EDP = createField(DSL.name("gid_edp"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.reference</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> REFERENCE = createField(DSL.name("reference"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.geometry1</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, Point> GEOMETRY1 = createField(DSL.name("geometry1"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "", new PointBinding());

    /**
     * The column <code>edp.vue_pei_edp_remocra.type_objet</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> TYPE_OBJET = createField(DSL.name("type_objet"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.prive</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, Integer> PRIVE = createField(DSL.name("prive"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.precision_pei_prive</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> PRECISION_PEI_PRIVE = createField(DSL.name("precision_pei_prive"), SQLDataType.VARCHAR(73), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.adresse</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> ADRESSE = createField(DSL.name("adresse"), SQLDataType.VARCHAR(107), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.notes_localisation</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> NOTES_LOCALISATION = createField(DSL.name("notes_localisation"), SQLDataType.VARCHAR(120), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.diametre</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, Integer> DIAMETRE = createField(DSL.name("diametre"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.modele</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> MODELE = createField(DSL.name("modele"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.diametre_canalisation</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> DIAMETRE_CANALISATION = createField(DSL.name("diametre_canalisation"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.materiau_canalisation</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> MATERIAU_CANALISATION = createField(DSL.name("materiau_canalisation"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_essai</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_ESSAI = createField(DSL.name("date_essai"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.essai_pression_statique</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, BigDecimal> ESSAI_PRESSION_STATIQUE = createField(DSL.name("essai_pression_statique"), SQLDataType.NUMERIC(8, 2), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.essai_pression_dynamique</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, BigDecimal> ESSAI_PRESSION_DYNAMIQUE = createField(DSL.name("essai_pression_dynamique"), SQLDataType.NUMERIC(8, 2), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.essai_debit</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, BigDecimal> ESSAI_DEBIT = createField(DSL.name("essai_debit"), SQLDataType.NUMERIC(8, 2), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.etat</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> ETAT = createField(DSL.name("etat"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_derniere_visite</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_DERNIERE_VISITE = createField(DSL.name("date_derniere_visite"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.type_derniere_visite</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, String> TYPE_DERNIERE_VISITE = createField(DSL.name("type_derniere_visite"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_maj_p</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_MAJ_P = createField(DSL.name("date_maj_p"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_maj_e</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_MAJ_E = createField(DSL.name("date_maj_e"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_maj_qp</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_MAJ_QP = createField(DSL.name("date_maj_qp"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_maj_cf</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_MAJ_CF = createField(DSL.name("date_maj_cf"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_maj_np</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_MAJ_NP = createField(DSL.name("date_maj_np"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_edp_remocra.date_maj_mj</code>.
     */
    public final TableField<VuePeiEdpRemocraRecord, LocalDateTime> DATE_MAJ_MJ = createField(DSL.name("date_maj_mj"), SQLDataType.LOCALDATETIME(6), this, "");

    private VuePeiEdpRemocra(Name alias, Table<VuePeiEdpRemocraRecord> aliased) {
        this(alias, aliased, null);
    }

    private VuePeiEdpRemocra(Name alias, Table<VuePeiEdpRemocraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>edp.vue_pei_edp_remocra</code> table reference
     */
    public VuePeiEdpRemocra(String alias) {
        this(DSL.name(alias), VUE_PEI_EDP_REMOCRA);
    }

    /**
     * Create an aliased <code>edp.vue_pei_edp_remocra</code> table reference
     */
    public VuePeiEdpRemocra(Name alias) {
        this(alias, VUE_PEI_EDP_REMOCRA);
    }

    /**
     * Create a <code>edp.vue_pei_edp_remocra</code> table reference
     */
    public VuePeiEdpRemocra() {
        this(DSL.name("vue_pei_edp_remocra"), null);
    }

    public <O extends Record> VuePeiEdpRemocra(Table<O> child, ForeignKey<O, VuePeiEdpRemocraRecord> key) {
        super(child, key, VUE_PEI_EDP_REMOCRA);
    }

    @Override
    public Schema getSchema() {
        return Edp.EDP;
    }

    @Override
    public Identity<VuePeiEdpRemocraRecord, Integer> getIdentity() {
        return (Identity<VuePeiEdpRemocraRecord, Integer>) super.getIdentity();
    }

    @Override
    public VuePeiEdpRemocra as(String alias) {
        return new VuePeiEdpRemocra(DSL.name(alias), this);
    }

    @Override
    public VuePeiEdpRemocra as(Name alias) {
        return new VuePeiEdpRemocra(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VuePeiEdpRemocra rename(String name) {
        return new VuePeiEdpRemocra(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VuePeiEdpRemocra rename(Name name) {
        return new VuePeiEdpRemocra(name, null);
    }
}
