/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables;


import fr.eaudeparis.syncremocra.db.model.Edp;
import fr.eaudeparis.syncremocra.db.model.tables.records.VuePeiMotifIndispoEdpRemocraRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VuePeiMotifIndispoEdpRemocra extends TableImpl<VuePeiMotifIndispoEdpRemocraRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>edp.vue_pei_motif_indispo_edp_remocra</code>
     */
    public static final VuePeiMotifIndispoEdpRemocra VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA = new VuePeiMotifIndispoEdpRemocra();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VuePeiMotifIndispoEdpRemocraRecord> getRecordType() {
        return VuePeiMotifIndispoEdpRemocraRecord.class;
    }

    /**
     * The column <code>edp.vue_pei_motif_indispo_edp_remocra.gid_edp</code>.
     */
    public final TableField<VuePeiMotifIndispoEdpRemocraRecord, Integer> GID_EDP = createField(DSL.name("gid_edp"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>edp.vue_pei_motif_indispo_edp_remocra.reference</code>.
     */
    public final TableField<VuePeiMotifIndispoEdpRemocraRecord, String> REFERENCE = createField(DSL.name("reference"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>edp.vue_pei_motif_indispo_edp_remocra.motif_indispo</code>.
     */
    public final TableField<VuePeiMotifIndispoEdpRemocraRecord, String> MOTIF_INDISPO = createField(DSL.name("motif_indispo"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>edp.vue_pei_motif_indispo_edp_remocra.statut_indispo</code>.
     */
    public final TableField<VuePeiMotifIndispoEdpRemocraRecord, String> STATUT_INDISPO = createField(DSL.name("statut_indispo"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>edp.vue_pei_motif_indispo_edp_remocra.date_debut</code>.
     */
    public final TableField<VuePeiMotifIndispoEdpRemocraRecord, LocalDateTime> DATE_DEBUT = createField(DSL.name("date_debut"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_motif_indispo_edp_remocra.date_fin_prevu</code>.
     */
    public final TableField<VuePeiMotifIndispoEdpRemocraRecord, LocalDateTime> DATE_FIN_PREVU = createField(DSL.name("date_fin_prevu"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>edp.vue_pei_motif_indispo_edp_remocra.date_maj_e</code>.
     */
    public final TableField<VuePeiMotifIndispoEdpRemocraRecord, LocalDateTime> DATE_MAJ_E = createField(DSL.name("date_maj_e"), SQLDataType.LOCALDATETIME(6), this, "");

    private VuePeiMotifIndispoEdpRemocra(Name alias, Table<VuePeiMotifIndispoEdpRemocraRecord> aliased) {
        this(alias, aliased, null);
    }

    private VuePeiMotifIndispoEdpRemocra(Name alias, Table<VuePeiMotifIndispoEdpRemocraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>edp.vue_pei_motif_indispo_edp_remocra</code> table reference
     */
    public VuePeiMotifIndispoEdpRemocra(String alias) {
        this(DSL.name(alias), VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA);
    }

    /**
     * Create an aliased <code>edp.vue_pei_motif_indispo_edp_remocra</code> table reference
     */
    public VuePeiMotifIndispoEdpRemocra(Name alias) {
        this(alias, VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA);
    }

    /**
     * Create a <code>edp.vue_pei_motif_indispo_edp_remocra</code> table reference
     */
    public VuePeiMotifIndispoEdpRemocra() {
        this(DSL.name("vue_pei_motif_indispo_edp_remocra"), null);
    }

    public <O extends Record> VuePeiMotifIndispoEdpRemocra(Table<O> child, ForeignKey<O, VuePeiMotifIndispoEdpRemocraRecord> key) {
        super(child, key, VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA);
    }

    @Override
    public Schema getSchema() {
        return Edp.EDP;
    }

    @Override
    public Identity<VuePeiMotifIndispoEdpRemocraRecord, Integer> getIdentity() {
        return (Identity<VuePeiMotifIndispoEdpRemocraRecord, Integer>) super.getIdentity();
    }

    @Override
    public VuePeiMotifIndispoEdpRemocra as(String alias) {
        return new VuePeiMotifIndispoEdpRemocra(DSL.name(alias), this);
    }

    @Override
    public VuePeiMotifIndispoEdpRemocra as(Name alias) {
        return new VuePeiMotifIndispoEdpRemocra(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VuePeiMotifIndispoEdpRemocra rename(String name) {
        return new VuePeiMotifIndispoEdpRemocra(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VuePeiMotifIndispoEdpRemocra rename(Name name) {
        return new VuePeiMotifIndispoEdpRemocra(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
