/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;


import fr.eaudeparis.syncremocra.db.model.tables.PullHydrantVisite;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PullHydrantVisiteRecord extends UpdatableRecordImpl<PullHydrantVisiteRecord> implements Record13<Integer, Long, LocalDateTime, String, Boolean, String, String, Integer, Integer, Double, Double, Double, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>edp.pull_hydrant_visite.id</code>.
     */
    public PullHydrantVisiteRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.hydrant</code>.
     */
    public PullHydrantVisiteRecord setHydrant(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.hydrant</code>.
     */
    public Long getHydrant() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.date</code>.
     */
    public PullHydrantVisiteRecord setDate(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.type</code>.
     */
    public PullHydrantVisiteRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.ctrl_debit_pression</code>.
     */
    public PullHydrantVisiteRecord setCtrlDebitPression(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.ctrl_debit_pression</code>.
     */
    public Boolean getCtrlDebitPression() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.agent1</code>.
     */
    public PullHydrantVisiteRecord setAgent1(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.agent1</code>.
     */
    public String getAgent1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.agent2</code>.
     */
    public PullHydrantVisiteRecord setAgent2(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.agent2</code>.
     */
    public String getAgent2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.debit</code>.
     */
    public PullHydrantVisiteRecord setDebit(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.debit</code>.
     */
    public Integer getDebit() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.debit_max</code>.
     */
    public PullHydrantVisiteRecord setDebitMax(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.debit_max</code>.
     */
    public Integer getDebitMax() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.pression</code>.
     */
    public PullHydrantVisiteRecord setPression(Double value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.pression</code>.
     */
    public Double getPression() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.pression_dyn</code>.
     */
    public PullHydrantVisiteRecord setPressionDyn(Double value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.pression_dyn</code>.
     */
    public Double getPressionDyn() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.pression_dyn_deb</code>.
     */
    public PullHydrantVisiteRecord setPressionDynDeb(Double value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.pression_dyn_deb</code>.
     */
    public Double getPressionDynDeb() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.observations</code>.
     */
    public PullHydrantVisiteRecord setObservations(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.observations</code>.
     */
    public String getObservations() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Long, LocalDateTime, String, Boolean, String, String, Integer, Integer, Double, Double, Double, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Long, LocalDateTime, String, Boolean, String, String, Integer, Integer, Double, Double, Double, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.ID;
    }

    @Override
    public Field<Long> field2() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.HYDRANT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.DATE;
    }

    @Override
    public Field<String> field4() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.TYPE;
    }

    @Override
    public Field<Boolean> field5() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.CTRL_DEBIT_PRESSION;
    }

    @Override
    public Field<String> field6() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.AGENT1;
    }

    @Override
    public Field<String> field7() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.AGENT2;
    }

    @Override
    public Field<Integer> field8() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.DEBIT;
    }

    @Override
    public Field<Integer> field9() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.DEBIT_MAX;
    }

    @Override
    public Field<Double> field10() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.PRESSION;
    }

    @Override
    public Field<Double> field11() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.PRESSION_DYN;
    }

    @Override
    public Field<Double> field12() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.PRESSION_DYN_DEB;
    }

    @Override
    public Field<String> field13() {
        return PullHydrantVisite.PULL_HYDRANT_VISITE.OBSERVATIONS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getHydrant();
    }

    @Override
    public LocalDateTime component3() {
        return getDate();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public Boolean component5() {
        return getCtrlDebitPression();
    }

    @Override
    public String component6() {
        return getAgent1();
    }

    @Override
    public String component7() {
        return getAgent2();
    }

    @Override
    public Integer component8() {
        return getDebit();
    }

    @Override
    public Integer component9() {
        return getDebitMax();
    }

    @Override
    public Double component10() {
        return getPression();
    }

    @Override
    public Double component11() {
        return getPressionDyn();
    }

    @Override
    public Double component12() {
        return getPressionDynDeb();
    }

    @Override
    public String component13() {
        return getObservations();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getHydrant();
    }

    @Override
    public LocalDateTime value3() {
        return getDate();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public Boolean value5() {
        return getCtrlDebitPression();
    }

    @Override
    public String value6() {
        return getAgent1();
    }

    @Override
    public String value7() {
        return getAgent2();
    }

    @Override
    public Integer value8() {
        return getDebit();
    }

    @Override
    public Integer value9() {
        return getDebitMax();
    }

    @Override
    public Double value10() {
        return getPression();
    }

    @Override
    public Double value11() {
        return getPressionDyn();
    }

    @Override
    public Double value12() {
        return getPressionDynDeb();
    }

    @Override
    public String value13() {
        return getObservations();
    }

    @Override
    public PullHydrantVisiteRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value2(Long value) {
        setHydrant(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value3(LocalDateTime value) {
        setDate(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value5(Boolean value) {
        setCtrlDebitPression(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value6(String value) {
        setAgent1(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value7(String value) {
        setAgent2(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value8(Integer value) {
        setDebit(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value9(Integer value) {
        setDebitMax(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value10(Double value) {
        setPression(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value11(Double value) {
        setPressionDyn(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value12(Double value) {
        setPressionDynDeb(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord value13(String value) {
        setObservations(value);
        return this;
    }

    @Override
    public PullHydrantVisiteRecord values(Integer value1, Long value2, LocalDateTime value3, String value4, Boolean value5, String value6, String value7, Integer value8, Integer value9, Double value10, Double value11, Double value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PullHydrantVisiteRecord
     */
    public PullHydrantVisiteRecord() {
        super(PullHydrantVisite.PULL_HYDRANT_VISITE);
    }

    /**
     * Create a detached, initialised PullHydrantVisiteRecord
     */
    public PullHydrantVisiteRecord(Integer id, Long hydrant, LocalDateTime date, String type, Boolean ctrlDebitPression, String agent1, String agent2, Integer debit, Integer debitMax, Double pression, Double pressionDyn, Double pressionDynDeb, String observations) {
        super(PullHydrantVisite.PULL_HYDRANT_VISITE);

        setId(id);
        setHydrant(hydrant);
        setDate(date);
        setType(type);
        setCtrlDebitPression(ctrlDebitPression);
        setAgent1(agent1);
        setAgent2(agent2);
        setDebit(debit);
        setDebitMax(debitMax);
        setPression(pression);
        setPressionDyn(pressionDyn);
        setPressionDynDeb(pressionDynDeb);
        setObservations(observations);
    }
}
