/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.PullHydrant;
import java.time.LocalDateTime;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PullHydrantRecord extends UpdatableRecordImpl<PullHydrantRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.pull_hydrant.id</code>. */
  public PullHydrantRecord setId(Integer value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.id</code>. */
  public Integer getId() {
    return (Integer) get(0);
  }

  /** Setter for <code>edp.pull_hydrant.numero</code>. */
  public PullHydrantRecord setNumero(String value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.numero</code>. */
  public String getNumero() {
    return (String) get(1);
  }

  /** Setter for <code>edp.pull_hydrant.date_modification</code>. */
  public PullHydrantRecord setDateModification(LocalDateTime value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.date_modification</code>. */
  public LocalDateTime getDateModification() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>edp.pull_hydrant.auteur_modification</code>. */
  public PullHydrantRecord setAuteurModification(String value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.auteur_modification</code>. */
  public String getAuteurModification() {
    return (String) get(3);
  }

  /** Setter for <code>edp.pull_hydrant.diametre</code>. */
  public PullHydrantRecord setDiametre(String value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.diametre</code>. */
  public String getDiametre() {
    return (String) get(4);
  }

  /** Setter for <code>edp.pull_hydrant.marque</code>. */
  public PullHydrantRecord setMarque(String value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.marque</code>. */
  public String getMarque() {
    return (String) get(5);
  }

  /** Setter for <code>edp.pull_hydrant.modele</code>. */
  public PullHydrantRecord setModele(String value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.modele</code>. */
  public String getModele() {
    return (String) get(6);
  }

  /** Setter for <code>edp.pull_hydrant.diametre_canalisation</code>. */
  public PullHydrantRecord setDiametreCanalisation(Integer value) {
    set(7, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.diametre_canalisation</code>. */
  public Integer getDiametreCanalisation() {
    return (Integer) get(7);
  }

  /** Setter for <code>edp.pull_hydrant.annee_fabrication</code>. */
  public PullHydrantRecord setAnneeFabrication(String value) {
    set(8, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.annee_fabrication</code>. */
  public String getAnneeFabrication() {
    return (String) get(8);
  }

  /** Setter for <code>edp.pull_hydrant.dispo_terrestre</code>. */
  public PullHydrantRecord setDispoTerrestre(String value) {
    set(9, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.dispo_terrestre</code>. */
  public String getDispoTerrestre() {
    return (String) get(9);
  }

  /** Setter for <code>edp.pull_hydrant.dispo_hbe</code>. */
  public PullHydrantRecord setDispoHbe(String value) {
    set(10, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.dispo_hbe</code>. */
  public String getDispoHbe() {
    return (String) get(10);
  }

  /** Setter for <code>edp.pull_hydrant.numero_voie</code>. */
  public PullHydrantRecord setNumeroVoie(Integer value) {
    set(11, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.numero_voie</code>. */
  public Integer getNumeroVoie() {
    return (Integer) get(11);
  }

  /** Setter for <code>edp.pull_hydrant.suffixe_voie</code>. */
  public PullHydrantRecord setSuffixeVoie(String value) {
    set(12, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.suffixe_voie</code>. */
  public String getSuffixeVoie() {
    return (String) get(12);
  }

  /** Setter for <code>edp.pull_hydrant.niveau</code>. */
  public PullHydrantRecord setNiveau(String value) {
    set(13, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.niveau</code>. */
  public String getNiveau() {
    return (String) get(13);
  }

  /** Setter for <code>edp.pull_hydrant.voie</code>. */
  public PullHydrantRecord setVoie(String value) {
    set(14, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.voie</code>. */
  public String getVoie() {
    return (String) get(14);
  }

  /** Setter for <code>edp.pull_hydrant.voie2</code>. */
  public PullHydrantRecord setVoie2(String value) {
    set(15, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.voie2</code>. */
  public String getVoie2() {
    return (String) get(15);
  }

  /** Setter for <code>edp.pull_hydrant.complement</code>. */
  public PullHydrantRecord setComplement(String value) {
    set(16, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.complement</code>. */
  public String getComplement() {
    return (String) get(16);
  }

  /** Setter for <code>edp.pull_hydrant.en_face</code>. */
  public PullHydrantRecord setEnFace(Boolean value) {
    set(17, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.en_face</code>. */
  public Boolean getEnFace() {
    return (Boolean) get(17);
  }

  /** Setter for <code>edp.pull_hydrant.commune</code>. */
  public PullHydrantRecord setCommune(String value) {
    set(18, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.commune</code>. */
  public String getCommune() {
    return (String) get(18);
  }

  /** Setter for <code>edp.pull_hydrant.domaine</code>. */
  public PullHydrantRecord setDomaine(String value) {
    set(19, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.domaine</code>. */
  public String getDomaine() {
    return (String) get(19);
  }

  /** Setter for <code>edp.pull_hydrant.nature</code>. */
  public PullHydrantRecord setNature(String value) {
    set(20, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.nature</code>. */
  public String getNature() {
    return (String) get(20);
  }

  /** Setter for <code>edp.pull_hydrant.nature_deci</code>. */
  public PullHydrantRecord setNatureDeci(String value) {
    set(21, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.nature_deci</code>. */
  public String getNatureDeci() {
    return (String) get(21);
  }

  /** Setter for <code>edp.pull_hydrant.indispo_temporaire</code>. */
  public PullHydrantRecord setIndispoTemporaire(Boolean value) {
    set(22, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant.indispo_temporaire</code>. */
  public Boolean getIndispoTemporaire() {
    return (Boolean) get(22);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached PullHydrantRecord */
  public PullHydrantRecord() {
    super(PullHydrant.PULL_HYDRANT);
  }

  /** Create a detached, initialised PullHydrantRecord */
  public PullHydrantRecord(
      Integer id,
      String numero,
      LocalDateTime dateModification,
      String auteurModification,
      String diametre,
      String marque,
      String modele,
      Integer diametreCanalisation,
      String anneeFabrication,
      String dispoTerrestre,
      String dispoHbe,
      Integer numeroVoie,
      String suffixeVoie,
      String niveau,
      String voie,
      String voie2,
      String complement,
      Boolean enFace,
      String commune,
      String domaine,
      String nature,
      String natureDeci,
      Boolean indispoTemporaire) {
    super(PullHydrant.PULL_HYDRANT);

    setId(id);
    setNumero(numero);
    setDateModification(dateModification);
    setAuteurModification(auteurModification);
    setDiametre(diametre);
    setMarque(marque);
    setModele(modele);
    setDiametreCanalisation(diametreCanalisation);
    setAnneeFabrication(anneeFabrication);
    setDispoTerrestre(dispoTerrestre);
    setDispoHbe(dispoHbe);
    setNumeroVoie(numeroVoie);
    setSuffixeVoie(suffixeVoie);
    setNiveau(niveau);
    setVoie(voie);
    setVoie2(voie2);
    setComplement(complement);
    setEnFace(enFace);
    setCommune(commune);
    setDomaine(domaine);
    setNature(nature);
    setNatureDeci(natureDeci);
    setIndispoTemporaire(indispoTemporaire);
  }
}
