/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.PullHydrantAnomalies;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PullHydrantAnomaliesRecord extends UpdatableRecordImpl<PullHydrantAnomaliesRecord>
    implements Record3<Integer, Long, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.pull_hydrant_anomalies.id</code>. */
  public PullHydrantAnomaliesRecord setId(Integer value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant_anomalies.id</code>. */
  public Integer getId() {
    return (Integer) get(0);
  }

  /** Setter for <code>edp.pull_hydrant_anomalies.visite</code>. */
  public PullHydrantAnomaliesRecord setVisite(Long value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant_anomalies.visite</code>. */
  public Long getVisite() {
    return (Long) get(1);
  }

  /** Setter for <code>edp.pull_hydrant_anomalies.code</code>. */
  public PullHydrantAnomaliesRecord setCode(String value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>edp.pull_hydrant_anomalies.code</code>. */
  public String getCode() {
    return (String) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<Integer, Long, String> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<Integer, Long, String> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<Integer> field1() {
    return PullHydrantAnomalies.PULL_HYDRANT_ANOMALIES.ID;
  }

  @Override
  public Field<Long> field2() {
    return PullHydrantAnomalies.PULL_HYDRANT_ANOMALIES.VISITE;
  }

  @Override
  public Field<String> field3() {
    return PullHydrantAnomalies.PULL_HYDRANT_ANOMALIES.CODE;
  }

  @Override
  public Integer component1() {
    return getId();
  }

  @Override
  public Long component2() {
    return getVisite();
  }

  @Override
  public String component3() {
    return getCode();
  }

  @Override
  public Integer value1() {
    return getId();
  }

  @Override
  public Long value2() {
    return getVisite();
  }

  @Override
  public String value3() {
    return getCode();
  }

  @Override
  public PullHydrantAnomaliesRecord value1(Integer value) {
    setId(value);
    return this;
  }

  @Override
  public PullHydrantAnomaliesRecord value2(Long value) {
    setVisite(value);
    return this;
  }

  @Override
  public PullHydrantAnomaliesRecord value3(String value) {
    setCode(value);
    return this;
  }

  @Override
  public PullHydrantAnomaliesRecord values(Integer value1, Long value2, String value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached PullHydrantAnomaliesRecord */
  public PullHydrantAnomaliesRecord() {
    super(PullHydrantAnomalies.PULL_HYDRANT_ANOMALIES);
  }

  /** Create a detached, initialised PullHydrantAnomaliesRecord */
  public PullHydrantAnomaliesRecord(Integer id, Long visite, String code) {
    super(PullHydrantAnomalies.PULL_HYDRANT_ANOMALIES);

    setId(id);
    setVisite(visite);
    setCode(code);
  }
}
