/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.PullMessage;
import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PullMessageRecord extends UpdatableRecordImpl<PullMessageRecord>
    implements Record6<Integer, LocalDateTime, LocalDateTime, String, String, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.pull_message.id</code>. */
  public PullMessageRecord setId(Integer value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.pull_message.id</code>. */
  public Integer getId() {
    return (Integer) get(0);
  }

  /** Setter for <code>edp.pull_message.date</code>. */
  public PullMessageRecord setDate(LocalDateTime value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.pull_message.date</code>. */
  public LocalDateTime getDate() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>edp.pull_message.date_modification</code>. */
  public PullMessageRecord setDateModification(LocalDateTime value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>edp.pull_message.date_modification</code>. */
  public LocalDateTime getDateModification() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>edp.pull_message.operation</code>. */
  public PullMessageRecord setOperation(String value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>edp.pull_message.operation</code>. */
  public String getOperation() {
    return (String) get(3);
  }

  /** Setter for <code>edp.pull_message.type</code>. */
  public PullMessageRecord setType(String value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>edp.pull_message.type</code>. */
  public String getType() {
    return (String) get(4);
  }

  /** Setter for <code>edp.pull_message.hydrant</code>. */
  public PullMessageRecord setHydrant(String value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>edp.pull_message.hydrant</code>. */
  public String getHydrant() {
    return (String) get(5);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record6 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row6<Integer, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
    return (Row6) super.fieldsRow();
  }

  @Override
  public Row6<Integer, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
    return (Row6) super.valuesRow();
  }

  @Override
  public Field<Integer> field1() {
    return PullMessage.PULL_MESSAGE.ID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return PullMessage.PULL_MESSAGE.DATE;
  }

  @Override
  public Field<LocalDateTime> field3() {
    return PullMessage.PULL_MESSAGE.DATE_MODIFICATION;
  }

  @Override
  public Field<String> field4() {
    return PullMessage.PULL_MESSAGE.OPERATION;
  }

  @Override
  public Field<String> field5() {
    return PullMessage.PULL_MESSAGE.TYPE;
  }

  @Override
  public Field<String> field6() {
    return PullMessage.PULL_MESSAGE.HYDRANT;
  }

  @Override
  public Integer component1() {
    return getId();
  }

  @Override
  public LocalDateTime component2() {
    return getDate();
  }

  @Override
  public LocalDateTime component3() {
    return getDateModification();
  }

  @Override
  public String component4() {
    return getOperation();
  }

  @Override
  public String component5() {
    return getType();
  }

  @Override
  public String component6() {
    return getHydrant();
  }

  @Override
  public Integer value1() {
    return getId();
  }

  @Override
  public LocalDateTime value2() {
    return getDate();
  }

  @Override
  public LocalDateTime value3() {
    return getDateModification();
  }

  @Override
  public String value4() {
    return getOperation();
  }

  @Override
  public String value5() {
    return getType();
  }

  @Override
  public String value6() {
    return getHydrant();
  }

  @Override
  public PullMessageRecord value1(Integer value) {
    setId(value);
    return this;
  }

  @Override
  public PullMessageRecord value2(LocalDateTime value) {
    setDate(value);
    return this;
  }

  @Override
  public PullMessageRecord value3(LocalDateTime value) {
    setDateModification(value);
    return this;
  }

  @Override
  public PullMessageRecord value4(String value) {
    setOperation(value);
    return this;
  }

  @Override
  public PullMessageRecord value5(String value) {
    setType(value);
    return this;
  }

  @Override
  public PullMessageRecord value6(String value) {
    setHydrant(value);
    return this;
  }

  @Override
  public PullMessageRecord values(
      Integer value1,
      LocalDateTime value2,
      LocalDateTime value3,
      String value4,
      String value5,
      String value6) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached PullMessageRecord */
  public PullMessageRecord() {
    super(PullMessage.PULL_MESSAGE);
  }

  /** Create a detached, initialised PullMessageRecord */
  public PullMessageRecord(
      Integer id,
      LocalDateTime date,
      LocalDateTime dateModification,
      String operation,
      String type,
      String hydrant) {
    super(PullMessage.PULL_MESSAGE);

    setId(id);
    setDate(date);
    setDateModification(dateModification);
    setOperation(operation);
    setType(type);
    setHydrant(hydrant);
  }
}
