/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.ReferentielMarquesModeles;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReferentielMarquesModelesRecord
    extends UpdatableRecordImpl<ReferentielMarquesModelesRecord>
    implements Record3<String, String, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.referentiel_marques_modeles.code_modele_edp</code>. */
  public ReferentielMarquesModelesRecord setCodeModeleEdp(String value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.referentiel_marques_modeles.code_modele_edp</code>. */
  public String getCodeModeleEdp() {
    return (String) get(0);
  }

  /** Setter for <code>edp.referentiel_marques_modeles.code_marque_remocra</code>. */
  public ReferentielMarquesModelesRecord setCodeMarqueRemocra(String value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.referentiel_marques_modeles.code_marque_remocra</code>. */
  public String getCodeMarqueRemocra() {
    return (String) get(1);
  }

  /** Setter for <code>edp.referentiel_marques_modeles.code_modele_remocra</code>. */
  public ReferentielMarquesModelesRecord setCodeModeleRemocra(String value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>edp.referentiel_marques_modeles.code_modele_remocra</code>. */
  public String getCodeModeleRemocra() {
    return (String) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record3<String, String, String> key() {
    return (Record3) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<String, String, String> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<String, String, String> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<String> field1() {
    return ReferentielMarquesModeles.REFERENTIEL_MARQUES_MODELES.CODE_MODELE_EDP;
  }

  @Override
  public Field<String> field2() {
    return ReferentielMarquesModeles.REFERENTIEL_MARQUES_MODELES.CODE_MARQUE_REMOCRA;
  }

  @Override
  public Field<String> field3() {
    return ReferentielMarquesModeles.REFERENTIEL_MARQUES_MODELES.CODE_MODELE_REMOCRA;
  }

  @Override
  public String component1() {
    return getCodeModeleEdp();
  }

  @Override
  public String component2() {
    return getCodeMarqueRemocra();
  }

  @Override
  public String component3() {
    return getCodeModeleRemocra();
  }

  @Override
  public String value1() {
    return getCodeModeleEdp();
  }

  @Override
  public String value2() {
    return getCodeMarqueRemocra();
  }

  @Override
  public String value3() {
    return getCodeModeleRemocra();
  }

  @Override
  public ReferentielMarquesModelesRecord value1(String value) {
    setCodeModeleEdp(value);
    return this;
  }

  @Override
  public ReferentielMarquesModelesRecord value2(String value) {
    setCodeMarqueRemocra(value);
    return this;
  }

  @Override
  public ReferentielMarquesModelesRecord value3(String value) {
    setCodeModeleRemocra(value);
    return this;
  }

  @Override
  public ReferentielMarquesModelesRecord values(String value1, String value2, String value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached ReferentielMarquesModelesRecord */
  public ReferentielMarquesModelesRecord() {
    super(ReferentielMarquesModeles.REFERENTIEL_MARQUES_MODELES);
  }

  /** Create a detached, initialised ReferentielMarquesModelesRecord */
  public ReferentielMarquesModelesRecord(
      String codeModeleEdp, String codeMarqueRemocra, String codeModeleRemocra) {
    super(ReferentielMarquesModeles.REFERENTIEL_MARQUES_MODELES);

    setCodeModeleEdp(codeModeleEdp);
    setCodeMarqueRemocra(codeMarqueRemocra);
    setCodeModeleRemocra(codeModeleRemocra);
  }
}
