/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.ReferentielAnomalies;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReferentielAnomaliesRecord extends UpdatableRecordImpl<ReferentielAnomaliesRecord>
    implements Record2<String, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.referentiel_anomalies.code_bspp</code>. */
  public ReferentielAnomaliesRecord setCodeBspp(String value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.referentiel_anomalies.code_bspp</code>. */
  public String getCodeBspp() {
    return (String) get(0);
  }

  /** Setter for <code>edp.referentiel_anomalies.code_edp</code>. */
  public ReferentielAnomaliesRecord setCodeEdp(String value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.referentiel_anomalies.code_edp</code>. */
  public String getCodeEdp() {
    return (String) get(1);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<String, String> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record2 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row2<String, String> fieldsRow() {
    return (Row2) super.fieldsRow();
  }

  @Override
  public Row2<String, String> valuesRow() {
    return (Row2) super.valuesRow();
  }

  @Override
  public Field<String> field1() {
    return ReferentielAnomalies.REFERENTIEL_ANOMALIES.CODE_BSPP;
  }

  @Override
  public Field<String> field2() {
    return ReferentielAnomalies.REFERENTIEL_ANOMALIES.CODE_EDP;
  }

  @Override
  public String component1() {
    return getCodeBspp();
  }

  @Override
  public String component2() {
    return getCodeEdp();
  }

  @Override
  public String value1() {
    return getCodeBspp();
  }

  @Override
  public String value2() {
    return getCodeEdp();
  }

  @Override
  public ReferentielAnomaliesRecord value1(String value) {
    setCodeBspp(value);
    return this;
  }

  @Override
  public ReferentielAnomaliesRecord value2(String value) {
    setCodeEdp(value);
    return this;
  }

  @Override
  public ReferentielAnomaliesRecord values(String value1, String value2) {
    value1(value1);
    value2(value2);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached ReferentielAnomaliesRecord */
  public ReferentielAnomaliesRecord() {
    super(ReferentielAnomalies.REFERENTIEL_ANOMALIES);
  }

  /** Create a detached, initialised ReferentielAnomaliesRecord */
  public ReferentielAnomaliesRecord(String codeBspp, String codeEdp) {
    super(ReferentielAnomalies.REFERENTIEL_ANOMALIES);

    setCodeBspp(codeBspp);
    setCodeEdp(codeEdp);
  }
}
