/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.TracabiliteIndispo;
import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TracabiliteIndispoRecord extends UpdatableRecordImpl<TracabiliteIndispoRecord>
    implements Record8<
        Integer, Long, String, String, LocalDateTime, LocalDateTime, LocalDateTime, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.tracabilite_indispo.id</code>. */
  public TracabiliteIndispoRecord setId(Integer value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.id</code>. */
  public Integer getId() {
    return (Integer) get(0);
  }

  /** Setter for <code>edp.tracabilite_indispo.id_traca_pei</code>. */
  public TracabiliteIndispoRecord setIdTracaPei(Long value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.id_traca_pei</code>. */
  public Long getIdTracaPei() {
    return (Long) get(1);
  }

  /** Setter for <code>edp.tracabilite_indispo.reference</code>. */
  public TracabiliteIndispoRecord setReference(String value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.reference</code>. */
  public String getReference() {
    return (String) get(2);
  }

  /** Setter for <code>edp.tracabilite_indispo.motif_indispo</code>. */
  public TracabiliteIndispoRecord setMotifIndispo(String value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.motif_indispo</code>. */
  public String getMotifIndispo() {
    return (String) get(3);
  }

  /** Setter for <code>edp.tracabilite_indispo.date_debut</code>. */
  public TracabiliteIndispoRecord setDateDebut(LocalDateTime value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.date_debut</code>. */
  public LocalDateTime getDateDebut() {
    return (LocalDateTime) get(4);
  }

  /** Setter for <code>edp.tracabilite_indispo.date_fin_prevue</code>. */
  public TracabiliteIndispoRecord setDateFinPrevue(LocalDateTime value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.date_fin_prevue</code>. */
  public LocalDateTime getDateFinPrevue() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>edp.tracabilite_indispo.date_traca</code>. */
  public TracabiliteIndispoRecord setDateTraca(LocalDateTime value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.date_traca</code>. */
  public LocalDateTime getDateTraca() {
    return (LocalDateTime) get(6);
  }

  /** Setter for <code>edp.tracabilite_indispo.statut_motif_indispo</code>. */
  public TracabiliteIndispoRecord setStatutMotifIndispo(String value) {
    set(7, value);
    return this;
  }

  /** Getter for <code>edp.tracabilite_indispo.statut_motif_indispo</code>. */
  public String getStatutMotifIndispo() {
    return (String) get(7);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row8<Integer, Long, String, String, LocalDateTime, LocalDateTime, LocalDateTime, String>
      fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  @Override
  public Row8<Integer, Long, String, String, LocalDateTime, LocalDateTime, LocalDateTime, String>
      valuesRow() {
    return (Row8) super.valuesRow();
  }

  @Override
  public Field<Integer> field1() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.ID;
  }

  @Override
  public Field<Long> field2() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.ID_TRACA_PEI;
  }

  @Override
  public Field<String> field3() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.REFERENCE;
  }

  @Override
  public Field<String> field4() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.MOTIF_INDISPO;
  }

  @Override
  public Field<LocalDateTime> field5() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.DATE_DEBUT;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.DATE_FIN_PREVUE;
  }

  @Override
  public Field<LocalDateTime> field7() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.DATE_TRACA;
  }

  @Override
  public Field<String> field8() {
    return TracabiliteIndispo.TRACABILITE_INDISPO.STATUT_MOTIF_INDISPO;
  }

  @Override
  public Integer component1() {
    return getId();
  }

  @Override
  public Long component2() {
    return getIdTracaPei();
  }

  @Override
  public String component3() {
    return getReference();
  }

  @Override
  public String component4() {
    return getMotifIndispo();
  }

  @Override
  public LocalDateTime component5() {
    return getDateDebut();
  }

  @Override
  public LocalDateTime component6() {
    return getDateFinPrevue();
  }

  @Override
  public LocalDateTime component7() {
    return getDateTraca();
  }

  @Override
  public String component8() {
    return getStatutMotifIndispo();
  }

  @Override
  public Integer value1() {
    return getId();
  }

  @Override
  public Long value2() {
    return getIdTracaPei();
  }

  @Override
  public String value3() {
    return getReference();
  }

  @Override
  public String value4() {
    return getMotifIndispo();
  }

  @Override
  public LocalDateTime value5() {
    return getDateDebut();
  }

  @Override
  public LocalDateTime value6() {
    return getDateFinPrevue();
  }

  @Override
  public LocalDateTime value7() {
    return getDateTraca();
  }

  @Override
  public String value8() {
    return getStatutMotifIndispo();
  }

  @Override
  public TracabiliteIndispoRecord value1(Integer value) {
    setId(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord value2(Long value) {
    setIdTracaPei(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord value3(String value) {
    setReference(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord value4(String value) {
    setMotifIndispo(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord value5(LocalDateTime value) {
    setDateDebut(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord value6(LocalDateTime value) {
    setDateFinPrevue(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord value7(LocalDateTime value) {
    setDateTraca(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord value8(String value) {
    setStatutMotifIndispo(value);
    return this;
  }

  @Override
  public TracabiliteIndispoRecord values(
      Integer value1,
      Long value2,
      String value3,
      String value4,
      LocalDateTime value5,
      LocalDateTime value6,
      LocalDateTime value7,
      String value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached TracabiliteIndispoRecord */
  public TracabiliteIndispoRecord() {
    super(TracabiliteIndispo.TRACABILITE_INDISPO);
  }

  /** Create a detached, initialised TracabiliteIndispoRecord */
  public TracabiliteIndispoRecord(
      Integer id,
      Long idTracaPei,
      String reference,
      String motifIndispo,
      LocalDateTime dateDebut,
      LocalDateTime dateFinPrevue,
      LocalDateTime dateTraca,
      String statutMotifIndispo) {
    super(TracabiliteIndispo.TRACABILITE_INDISPO);

    setId(id);
    setIdTracaPei(idTracaPei);
    setReference(reference);
    setMotifIndispo(motifIndispo);
    setDateDebut(dateDebut);
    setDateFinPrevue(dateFinPrevue);
    setDateTraca(dateTraca);
    setStatutMotifIndispo(statutMotifIndispo);
  }
}
