/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.VueErreursEdp;
import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VueErreursEdpRecord extends TableRecordImpl<VueErreursEdpRecord>
    implements Record8<LocalDateTime, Boolean, String, String, String, String, String, String> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.vue_erreurs_edp.date</code>. */
  public VueErreursEdpRecord setDate(LocalDateTime value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.date</code>. */
  public LocalDateTime getDate() {
    return (LocalDateTime) get(0);
  }

  /** Setter for <code>edp.vue_erreurs_edp.notifie</code>. */
  public VueErreursEdpRecord setNotifie(Boolean value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.notifie</code>. */
  public Boolean getNotifie() {
    return (Boolean) get(1);
  }

  /** Setter for <code>edp.vue_erreurs_edp.message_erreur</code>. */
  public VueErreursEdpRecord setMessageErreur(String value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.message_erreur</code>. */
  public String getMessageErreur() {
    return (String) get(2);
  }

  /** Setter for <code>edp.vue_erreurs_edp.message_action</code>. */
  public VueErreursEdpRecord setMessageAction(String value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.message_action</code>. */
  public String getMessageAction() {
    return (String) get(3);
  }

  /** Setter for <code>edp.vue_erreurs_edp.contexte</code>. */
  public VueErreursEdpRecord setContexte(String value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.contexte</code>. */
  public String getContexte() {
    return (String) get(4);
  }

  /** Setter for <code>edp.vue_erreurs_edp.type</code>. */
  public VueErreursEdpRecord setType(String value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.type</code>. */
  public String getType() {
    return (String) get(5);
  }

  /** Setter for <code>edp.vue_erreurs_edp.reference</code>. */
  public VueErreursEdpRecord setReference(String value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.reference</code>. */
  public String getReference() {
    return (String) get(6);
  }

  /** Setter for <code>edp.vue_erreurs_edp.json</code>. */
  public VueErreursEdpRecord setJson(String value) {
    set(7, value);
    return this;
  }

  /** Getter for <code>edp.vue_erreurs_edp.json</code>. */
  public String getJson() {
    return (String) get(7);
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row8<LocalDateTime, Boolean, String, String, String, String, String, String> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  @Override
  public Row8<LocalDateTime, Boolean, String, String, String, String, String, String> valuesRow() {
    return (Row8) super.valuesRow();
  }

  @Override
  public Field<LocalDateTime> field1() {
    return VueErreursEdp.VUE_ERREURS_EDP.DATE;
  }

  @Override
  public Field<Boolean> field2() {
    return VueErreursEdp.VUE_ERREURS_EDP.NOTIFIE;
  }

  @Override
  public Field<String> field3() {
    return VueErreursEdp.VUE_ERREURS_EDP.MESSAGE_ERREUR;
  }

  @Override
  public Field<String> field4() {
    return VueErreursEdp.VUE_ERREURS_EDP.MESSAGE_ACTION;
  }

  @Override
  public Field<String> field5() {
    return VueErreursEdp.VUE_ERREURS_EDP.CONTEXTE;
  }

  @Override
  public Field<String> field6() {
    return VueErreursEdp.VUE_ERREURS_EDP.TYPE;
  }

  @Override
  public Field<String> field7() {
    return VueErreursEdp.VUE_ERREURS_EDP.REFERENCE;
  }

  @Override
  public Field<String> field8() {
    return VueErreursEdp.VUE_ERREURS_EDP.JSON;
  }

  @Override
  public LocalDateTime component1() {
    return getDate();
  }

  @Override
  public Boolean component2() {
    return getNotifie();
  }

  @Override
  public String component3() {
    return getMessageErreur();
  }

  @Override
  public String component4() {
    return getMessageAction();
  }

  @Override
  public String component5() {
    return getContexte();
  }

  @Override
  public String component6() {
    return getType();
  }

  @Override
  public String component7() {
    return getReference();
  }

  @Override
  public String component8() {
    return getJson();
  }

  @Override
  public LocalDateTime value1() {
    return getDate();
  }

  @Override
  public Boolean value2() {
    return getNotifie();
  }

  @Override
  public String value3() {
    return getMessageErreur();
  }

  @Override
  public String value4() {
    return getMessageAction();
  }

  @Override
  public String value5() {
    return getContexte();
  }

  @Override
  public String value6() {
    return getType();
  }

  @Override
  public String value7() {
    return getReference();
  }

  @Override
  public String value8() {
    return getJson();
  }

  @Override
  public VueErreursEdpRecord value1(LocalDateTime value) {
    setDate(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord value2(Boolean value) {
    setNotifie(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord value3(String value) {
    setMessageErreur(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord value4(String value) {
    setMessageAction(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord value5(String value) {
    setContexte(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord value6(String value) {
    setType(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord value7(String value) {
    setReference(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord value8(String value) {
    setJson(value);
    return this;
  }

  @Override
  public VueErreursEdpRecord values(
      LocalDateTime value1,
      Boolean value2,
      String value3,
      String value4,
      String value5,
      String value6,
      String value7,
      String value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached VueErreursEdpRecord */
  public VueErreursEdpRecord() {
    super(VueErreursEdp.VUE_ERREURS_EDP);
  }

  /** Create a detached, initialised VueErreursEdpRecord */
  public VueErreursEdpRecord(
      LocalDateTime date,
      Boolean notifie,
      String messageErreur,
      String messageAction,
      String contexte,
      String type,
      String reference,
      String json) {
    super(VueErreursEdp.VUE_ERREURS_EDP);

    setDate(date);
    setNotifie(notifie);
    setMessageErreur(messageErreur);
    setMessageAction(messageAction);
    setContexte(contexte);
    setType(type);
    setReference(reference);
    setJson(json);
  }
}
