/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;


import fr.eaudeparis.syncremocra.db.model.tables.VuePeiEdpRemocra;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;
import org.locationtech.jts.geom.Point;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VuePeiEdpRemocraRecord extends TableRecordImpl<VuePeiEdpRemocraRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.gid_edp</code>.
     */
    public VuePeiEdpRemocraRecord setGidEdp(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.gid_edp</code>.
     */
    public Integer getGidEdp() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.reference</code>.
     */
    public VuePeiEdpRemocraRecord setReference(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.reference</code>.
     */
    public String getReference() {
        return (String) get(1);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.geometry1</code>.
     */
    public VuePeiEdpRemocraRecord setGeometry1(Point value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.geometry1</code>.
     */
    public Point getGeometry1() {
        return (Point) get(2);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.type_objet</code>.
     */
    public VuePeiEdpRemocraRecord setTypeObjet(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.type_objet</code>.
     */
    public String getTypeObjet() {
        return (String) get(3);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.prive</code>.
     */
    public VuePeiEdpRemocraRecord setPrive(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.prive</code>.
     */
    public Integer getPrive() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.precision_pei_prive</code>.
     */
    public VuePeiEdpRemocraRecord setPrecisionPeiPrive(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.precision_pei_prive</code>.
     */
    public String getPrecisionPeiPrive() {
        return (String) get(5);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.adresse</code>.
     */
    public VuePeiEdpRemocraRecord setAdresse(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.adresse</code>.
     */
    public String getAdresse() {
        return (String) get(6);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.notes_localisation</code>.
     */
    public VuePeiEdpRemocraRecord setNotesLocalisation(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.notes_localisation</code>.
     */
    public String getNotesLocalisation() {
        return (String) get(7);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.diametre</code>.
     */
    public VuePeiEdpRemocraRecord setDiametre(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.diametre</code>.
     */
    public Integer getDiametre() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.modele</code>.
     */
    public VuePeiEdpRemocraRecord setModele(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.modele</code>.
     */
    public String getModele() {
        return (String) get(9);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.diametre_canalisation</code>.
     */
    public VuePeiEdpRemocraRecord setDiametreCanalisation(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.diametre_canalisation</code>.
     */
    public String getDiametreCanalisation() {
        return (String) get(10);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.materiau_canalisation</code>.
     */
    public VuePeiEdpRemocraRecord setMateriauCanalisation(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.materiau_canalisation</code>.
     */
    public String getMateriauCanalisation() {
        return (String) get(11);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_essai</code>.
     */
    public VuePeiEdpRemocraRecord setDateEssai(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_essai</code>.
     */
    public LocalDateTime getDateEssai() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.essai_pression_statique</code>.
     */
    public VuePeiEdpRemocraRecord setEssaiPressionStatique(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.essai_pression_statique</code>.
     */
    public BigDecimal getEssaiPressionStatique() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.essai_pression_dynamique</code>.
     */
    public VuePeiEdpRemocraRecord setEssaiPressionDynamique(BigDecimal value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.essai_pression_dynamique</code>.
     */
    public BigDecimal getEssaiPressionDynamique() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.essai_debit</code>.
     */
    public VuePeiEdpRemocraRecord setEssaiDebit(BigDecimal value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.essai_debit</code>.
     */
    public BigDecimal getEssaiDebit() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.etat</code>.
     */
    public VuePeiEdpRemocraRecord setEtat(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.etat</code>.
     */
    public String getEtat() {
        return (String) get(16);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_derniere_visite</code>.
     */
    public VuePeiEdpRemocraRecord setDateDerniereVisite(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_derniere_visite</code>.
     */
    public LocalDateTime getDateDerniereVisite() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.type_derniere_visite</code>.
     */
    public VuePeiEdpRemocraRecord setTypeDerniereVisite(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.type_derniere_visite</code>.
     */
    public String getTypeDerniereVisite() {
        return (String) get(18);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_maj_p</code>.
     */
    public VuePeiEdpRemocraRecord setDateMajP(LocalDateTime value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_maj_p</code>.
     */
    public LocalDateTime getDateMajP() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_maj_e</code>.
     */
    public VuePeiEdpRemocraRecord setDateMajE(LocalDateTime value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_maj_e</code>.
     */
    public LocalDateTime getDateMajE() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_maj_qp</code>.
     */
    public VuePeiEdpRemocraRecord setDateMajQp(LocalDateTime value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_maj_qp</code>.
     */
    public LocalDateTime getDateMajQp() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_maj_cf</code>.
     */
    public VuePeiEdpRemocraRecord setDateMajCf(LocalDateTime value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_maj_cf</code>.
     */
    public LocalDateTime getDateMajCf() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_maj_np</code>.
     */
    public VuePeiEdpRemocraRecord setDateMajNp(LocalDateTime value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_maj_np</code>.
     */
    public LocalDateTime getDateMajNp() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>edp.vue_pei_edp_remocra.date_maj_mj</code>.
     */
    public VuePeiEdpRemocraRecord setDateMajMj(LocalDateTime value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_edp_remocra.date_maj_mj</code>.
     */
    public LocalDateTime getDateMajMj() {
        return (LocalDateTime) get(24);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VuePeiEdpRemocraRecord
     */
    public VuePeiEdpRemocraRecord() {
        super(VuePeiEdpRemocra.VUE_PEI_EDP_REMOCRA);
    }

    /**
     * Create a detached, initialised VuePeiEdpRemocraRecord
     */
    public VuePeiEdpRemocraRecord(Integer gidEdp, String reference, Point geometry1, String typeObjet, Integer prive, String precisionPeiPrive, String adresse, String notesLocalisation, Integer diametre, String modele, String diametreCanalisation, String materiauCanalisation, LocalDateTime dateEssai, BigDecimal essaiPressionStatique, BigDecimal essaiPressionDynamique, BigDecimal essaiDebit, String etat, LocalDateTime dateDerniereVisite, String typeDerniereVisite, LocalDateTime dateMajP, LocalDateTime dateMajE, LocalDateTime dateMajQp, LocalDateTime dateMajCf, LocalDateTime dateMajNp, LocalDateTime dateMajMj) {
        super(VuePeiEdpRemocra.VUE_PEI_EDP_REMOCRA);

        setGidEdp(gidEdp);
        setReference(reference);
        setGeometry1(geometry1);
        setTypeObjet(typeObjet);
        setPrive(prive);
        setPrecisionPeiPrive(precisionPeiPrive);
        setAdresse(adresse);
        setNotesLocalisation(notesLocalisation);
        setDiametre(diametre);
        setModele(modele);
        setDiametreCanalisation(diametreCanalisation);
        setMateriauCanalisation(materiauCanalisation);
        setDateEssai(dateEssai);
        setEssaiPressionStatique(essaiPressionStatique);
        setEssaiPressionDynamique(essaiPressionDynamique);
        setEssaiDebit(essaiDebit);
        setEtat(etat);
        setDateDerniereVisite(dateDerniereVisite);
        setTypeDerniereVisite(typeDerniereVisite);
        setDateMajP(dateMajP);
        setDateMajE(dateMajE);
        setDateMajQp(dateMajQp);
        setDateMajCf(dateMajCf);
        setDateMajNp(dateMajNp);
        setDateMajMj(dateMajMj);
    }
}
