/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;


import fr.eaudeparis.syncremocra.db.model.tables.VuePeiMotifIndispoEdpRemocra;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VuePeiMotifIndispoEdpRemocraRecord extends TableRecordImpl<VuePeiMotifIndispoEdpRemocraRecord> implements Record6<Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>edp.vue_pei_motif_indispo_edp_remocra.gid_edp</code>.
     */
    public VuePeiMotifIndispoEdpRemocraRecord setGidEdp(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_motif_indispo_edp_remocra.gid_edp</code>.
     */
    public Integer getGidEdp() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>edp.vue_pei_motif_indispo_edp_remocra.reference</code>.
     */
    public VuePeiMotifIndispoEdpRemocraRecord setReference(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_motif_indispo_edp_remocra.reference</code>.
     */
    public String getReference() {
        return (String) get(1);
    }

    /**
     * Setter for <code>edp.vue_pei_motif_indispo_edp_remocra.motif_indispo</code>.
     */
    public VuePeiMotifIndispoEdpRemocraRecord setMotifIndispo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_motif_indispo_edp_remocra.motif_indispo</code>.
     */
    public String getMotifIndispo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>edp.vue_pei_motif_indispo_edp_remocra.statut_indispo</code>.
     */
    public VuePeiMotifIndispoEdpRemocraRecord setStatutIndispo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_motif_indispo_edp_remocra.statut_indispo</code>.
     */
    public String getStatutIndispo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>edp.vue_pei_motif_indispo_edp_remocra.date_debut</code>.
     */
    public VuePeiMotifIndispoEdpRemocraRecord setDateDebut(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_motif_indispo_edp_remocra.date_debut</code>.
     */
    public LocalDateTime getDateDebut() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>edp.vue_pei_motif_indispo_edp_remocra.date_fin_prevue</code>.
     */
    public VuePeiMotifIndispoEdpRemocraRecord setDateFinPrevue(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>edp.vue_pei_motif_indispo_edp_remocra.date_fin_prevue</code>.
     */
    public LocalDateTime getDateFinPrevue() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA.GID_EDP;
    }

    @Override
    public Field<String> field2() {
        return VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA.REFERENCE;
    }

    @Override
    public Field<String> field3() {
        return VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA.MOTIF_INDISPO;
    }

    @Override
    public Field<String> field4() {
        return VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA.STATUT_INDISPO;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA.DATE_DEBUT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA.DATE_FIN_PREVUE;
    }

    @Override
    public Integer component1() {
        return getGidEdp();
    }

    @Override
    public String component2() {
        return getReference();
    }

    @Override
    public String component3() {
        return getMotifIndispo();
    }

    @Override
    public String component4() {
        return getStatutIndispo();
    }

    @Override
    public LocalDateTime component5() {
        return getDateDebut();
    }

    @Override
    public LocalDateTime component6() {
        return getDateFinPrevue();
    }

    @Override
    public Integer value1() {
        return getGidEdp();
    }

    @Override
    public String value2() {
        return getReference();
    }

    @Override
    public String value3() {
        return getMotifIndispo();
    }

    @Override
    public String value4() {
        return getStatutIndispo();
    }

    @Override
    public LocalDateTime value5() {
        return getDateDebut();
    }

    @Override
    public LocalDateTime value6() {
        return getDateFinPrevue();
    }

    @Override
    public VuePeiMotifIndispoEdpRemocraRecord value1(Integer value) {
        setGidEdp(value);
        return this;
    }

    @Override
    public VuePeiMotifIndispoEdpRemocraRecord value2(String value) {
        setReference(value);
        return this;
    }

    @Override
    public VuePeiMotifIndispoEdpRemocraRecord value3(String value) {
        setMotifIndispo(value);
        return this;
    }

    @Override
    public VuePeiMotifIndispoEdpRemocraRecord value4(String value) {
        setStatutIndispo(value);
        return this;
    }

    @Override
    public VuePeiMotifIndispoEdpRemocraRecord value5(LocalDateTime value) {
        setDateDebut(value);
        return this;
    }

    @Override
    public VuePeiMotifIndispoEdpRemocraRecord value6(LocalDateTime value) {
        setDateFinPrevue(value);
        return this;
    }

    @Override
    public VuePeiMotifIndispoEdpRemocraRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VuePeiMotifIndispoEdpRemocraRecord
     */
    public VuePeiMotifIndispoEdpRemocraRecord() {
        super(VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA);
    }

    /**
     * Create a detached, initialised VuePeiMotifIndispoEdpRemocraRecord
     */
    public VuePeiMotifIndispoEdpRemocraRecord(Integer gidEdp, String reference, String motifIndispo, String statutIndispo, LocalDateTime dateDebut, LocalDateTime dateFinPrevue) {
        super(VuePeiMotifIndispoEdpRemocra.VUE_PEI_MOTIF_INDISPO_EDP_REMOCRA);

        setGidEdp(gidEdp);
        setReference(reference);
        setMotifIndispo(motifIndispo);
        setStatutIndispo(statutIndispo);
        setDateDebut(dateDebut);
        setDateFinPrevue(dateFinPrevue);
    }
}
