/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.records;

import fr.eaudeparis.syncremocra.db.model.tables.VueVisite;
import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VueVisiteRecord extends TableRecordImpl<VueVisiteRecord>
    implements Record8<
        Integer, String, LocalDateTime, String, Integer, Integer, Integer, LocalDateTime> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>edp.vue_visite.gid_edp</code>. */
  public VueVisiteRecord setGidEdp(Integer value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.gid_edp</code>. */
  public Integer getGidEdp() {
    return (Integer) get(0);
  }

  /** Setter for <code>edp.vue_visite.reference</code>. */
  public VueVisiteRecord setReference(String value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.reference</code>. */
  public String getReference() {
    return (String) get(1);
  }

  /** Setter for <code>edp.vue_visite.date_visite</code>. */
  public VueVisiteRecord setDateVisite(LocalDateTime value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.date_visite</code>. */
  public LocalDateTime getDateVisite() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>edp.vue_visite.type_visite</code>. */
  public VueVisiteRecord setTypeVisite(String value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.type_visite</code>. */
  public String getTypeVisite() {
    return (String) get(3);
  }

  /** Setter for <code>edp.vue_visite.essaie_pression_static</code>. */
  public VueVisiteRecord setEssaiePressionStatic(Integer value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.essaie_pression_static</code>. */
  public Integer getEssaiePressionStatic() {
    return (Integer) get(4);
  }

  /** Setter for <code>edp.vue_visite.essaie_pression_dynamique</code>. */
  public VueVisiteRecord setEssaiePressionDynamique(Integer value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.essaie_pression_dynamique</code>. */
  public Integer getEssaiePressionDynamique() {
    return (Integer) get(5);
  }

  /** Setter for <code>edp.vue_visite.essaie_debit</code>. */
  public VueVisiteRecord setEssaieDebit(Integer value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.essaie_debit</code>. */
  public Integer getEssaieDebit() {
    return (Integer) get(6);
  }

  /** Setter for <code>edp.vue_visite.date_maj_e</code>. */
  public VueVisiteRecord setDateMajE(LocalDateTime value) {
    set(7, value);
    return this;
  }

  /** Getter for <code>edp.vue_visite.date_maj_e</code>. */
  public LocalDateTime getDateMajE() {
    return (LocalDateTime) get(7);
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row8<Integer, String, LocalDateTime, String, Integer, Integer, Integer, LocalDateTime>
      fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  @Override
  public Row8<Integer, String, LocalDateTime, String, Integer, Integer, Integer, LocalDateTime>
      valuesRow() {
    return (Row8) super.valuesRow();
  }

  @Override
  public Field<Integer> field1() {
    return VueVisite.VUE_VISITE.GID_EDP;
  }

  @Override
  public Field<String> field2() {
    return VueVisite.VUE_VISITE.REFERENCE;
  }

  @Override
  public Field<LocalDateTime> field3() {
    return VueVisite.VUE_VISITE.DATE_VISITE;
  }

  @Override
  public Field<String> field4() {
    return VueVisite.VUE_VISITE.TYPE_VISITE;
  }

  @Override
  public Field<Integer> field5() {
    return VueVisite.VUE_VISITE.ESSAIE_PRESSION_STATIC;
  }

  @Override
  public Field<Integer> field6() {
    return VueVisite.VUE_VISITE.ESSAIE_PRESSION_DYNAMIQUE;
  }

  @Override
  public Field<Integer> field7() {
    return VueVisite.VUE_VISITE.ESSAIE_DEBIT;
  }

  @Override
  public Field<LocalDateTime> field8() {
    return VueVisite.VUE_VISITE.DATE_MAJ_E;
  }

  @Override
  public Integer component1() {
    return getGidEdp();
  }

  @Override
  public String component2() {
    return getReference();
  }

  @Override
  public LocalDateTime component3() {
    return getDateVisite();
  }

  @Override
  public String component4() {
    return getTypeVisite();
  }

  @Override
  public Integer component5() {
    return getEssaiePressionStatic();
  }

  @Override
  public Integer component6() {
    return getEssaiePressionDynamique();
  }

  @Override
  public Integer component7() {
    return getEssaieDebit();
  }

  @Override
  public LocalDateTime component8() {
    return getDateMajE();
  }

  @Override
  public Integer value1() {
    return getGidEdp();
  }

  @Override
  public String value2() {
    return getReference();
  }

  @Override
  public LocalDateTime value3() {
    return getDateVisite();
  }

  @Override
  public String value4() {
    return getTypeVisite();
  }

  @Override
  public Integer value5() {
    return getEssaiePressionStatic();
  }

  @Override
  public Integer value6() {
    return getEssaiePressionDynamique();
  }

  @Override
  public Integer value7() {
    return getEssaieDebit();
  }

  @Override
  public LocalDateTime value8() {
    return getDateMajE();
  }

  @Override
  public VueVisiteRecord value1(Integer value) {
    setGidEdp(value);
    return this;
  }

  @Override
  public VueVisiteRecord value2(String value) {
    setReference(value);
    return this;
  }

  @Override
  public VueVisiteRecord value3(LocalDateTime value) {
    setDateVisite(value);
    return this;
  }

  @Override
  public VueVisiteRecord value4(String value) {
    setTypeVisite(value);
    return this;
  }

  @Override
  public VueVisiteRecord value5(Integer value) {
    setEssaiePressionStatic(value);
    return this;
  }

  @Override
  public VueVisiteRecord value6(Integer value) {
    setEssaiePressionDynamique(value);
    return this;
  }

  @Override
  public VueVisiteRecord value7(Integer value) {
    setEssaieDebit(value);
    return this;
  }

  @Override
  public VueVisiteRecord value8(LocalDateTime value) {
    setDateMajE(value);
    return this;
  }

  @Override
  public VueVisiteRecord values(
      Integer value1,
      String value2,
      LocalDateTime value3,
      String value4,
      Integer value5,
      Integer value6,
      Integer value7,
      LocalDateTime value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached VueVisiteRecord */
  public VueVisiteRecord() {
    super(VueVisite.VUE_VISITE);
  }

  /** Create a detached, initialised VueVisiteRecord */
  public VueVisiteRecord(
      Integer gidEdp,
      String reference,
      LocalDateTime dateVisite,
      String typeVisite,
      Integer essaiePressionStatic,
      Integer essaiePressionDynamique,
      Integer essaieDebit,
      LocalDateTime dateMajE) {
    super(VueVisite.VUE_VISITE);

    setGidEdp(gidEdp);
    setReference(reference);
    setDateVisite(dateVisite);
    setTypeVisite(typeVisite);
    setEssaiePressionStatic(essaiePressionStatic);
    setEssaiePressionDynamique(essaiePressionDynamique);
    setEssaieDebit(essaieDebit);
    setDateMajE(dateMajE);
  }
}
