/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.pojos;

import java.io.Serializable;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Parametres implements Serializable {

  private static final long serialVersionUID = 1L;

  private String code;
  private String valeur;

  public Parametres() {}

  public Parametres(Parametres value) {
    this.code = value.code;
    this.valeur = value.valeur;
  }

  public Parametres(String code, String valeur) {
    this.code = code;
    this.valeur = valeur;
  }

  /** Getter for <code>edp.parametres.code</code>. */
  public String getCode() {
    return this.code;
  }

  /** Setter for <code>edp.parametres.code</code>. */
  public Parametres setCode(String code) {
    this.code = code;
    return this;
  }

  /** Getter for <code>edp.parametres.valeur</code>. */
  public String getValeur() {
    return this.valeur;
  }

  /** Setter for <code>edp.parametres.valeur</code>. */
  public Parametres setValeur(String valeur) {
    this.valeur = valeur;
    return this;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Parametres (");

    sb.append(code);
    sb.append(", ").append(valeur);

    sb.append(")");
    return sb.toString();
  }
}
