/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PullHydrant implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        numero;
    private LocalDateTime dateModification;
    private String        auteurModification;
    private String        diametre;
    private String        marque;
    private String        modele;
    private Integer       diametreCanalisation;
    private String        anneeFabrication;
    private String        dispoTerrestre;
    private String        dispoHbe;
    private Integer       numeroVoie;
    private String        suffixeVoie;
    private String        niveau;
    private String        voie;
    private String        voie2;
    private String        complement;
    private Boolean       enFace;
    private String        commune;
    private String        domaine;
    private String        nature;
    private String        natureDeci;
    private Boolean       indispoTemporaire;

    public PullHydrant() {}

    public PullHydrant(PullHydrant value) {
        this.id = value.id;
        this.numero = value.numero;
        this.dateModification = value.dateModification;
        this.auteurModification = value.auteurModification;
        this.diametre = value.diametre;
        this.marque = value.marque;
        this.modele = value.modele;
        this.diametreCanalisation = value.diametreCanalisation;
        this.anneeFabrication = value.anneeFabrication;
        this.dispoTerrestre = value.dispoTerrestre;
        this.dispoHbe = value.dispoHbe;
        this.numeroVoie = value.numeroVoie;
        this.suffixeVoie = value.suffixeVoie;
        this.niveau = value.niveau;
        this.voie = value.voie;
        this.voie2 = value.voie2;
        this.complement = value.complement;
        this.enFace = value.enFace;
        this.commune = value.commune;
        this.domaine = value.domaine;
        this.nature = value.nature;
        this.natureDeci = value.natureDeci;
        this.indispoTemporaire = value.indispoTemporaire;
    }

    public PullHydrant(
        Integer       id,
        String        numero,
        LocalDateTime dateModification,
        String        auteurModification,
        String        diametre,
        String        marque,
        String        modele,
        Integer       diametreCanalisation,
        String        anneeFabrication,
        String        dispoTerrestre,
        String        dispoHbe,
        Integer       numeroVoie,
        String        suffixeVoie,
        String        niveau,
        String        voie,
        String        voie2,
        String        complement,
        Boolean       enFace,
        String        commune,
        String        domaine,
        String        nature,
        String        natureDeci,
        Boolean       indispoTemporaire
    ) {
        this.id = id;
        this.numero = numero;
        this.dateModification = dateModification;
        this.auteurModification = auteurModification;
        this.diametre = diametre;
        this.marque = marque;
        this.modele = modele;
        this.diametreCanalisation = diametreCanalisation;
        this.anneeFabrication = anneeFabrication;
        this.dispoTerrestre = dispoTerrestre;
        this.dispoHbe = dispoHbe;
        this.numeroVoie = numeroVoie;
        this.suffixeVoie = suffixeVoie;
        this.niveau = niveau;
        this.voie = voie;
        this.voie2 = voie2;
        this.complement = complement;
        this.enFace = enFace;
        this.commune = commune;
        this.domaine = domaine;
        this.nature = nature;
        this.natureDeci = natureDeci;
        this.indispoTemporaire = indispoTemporaire;
    }

    /**
     * Getter for <code>edp.pull_hydrant.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>edp.pull_hydrant.id</code>.
     */
    public PullHydrant setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.numero</code>.
     */
    public String getNumero() {
        return this.numero;
    }

    /**
     * Setter for <code>edp.pull_hydrant.numero</code>.
     */
    public PullHydrant setNumero(String numero) {
        this.numero = numero;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.date_modification</code>.
     */
    public LocalDateTime getDateModification() {
        return this.dateModification;
    }

    /**
     * Setter for <code>edp.pull_hydrant.date_modification</code>.
     */
    public PullHydrant setDateModification(LocalDateTime dateModification) {
        this.dateModification = dateModification;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.auteur_modification</code>.
     */
    public String getAuteurModification() {
        return this.auteurModification;
    }

    /**
     * Setter for <code>edp.pull_hydrant.auteur_modification</code>.
     */
    public PullHydrant setAuteurModification(String auteurModification) {
        this.auteurModification = auteurModification;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.diametre</code>.
     */
    public String getDiametre() {
        return this.diametre;
    }

    /**
     * Setter for <code>edp.pull_hydrant.diametre</code>.
     */
    public PullHydrant setDiametre(String diametre) {
        this.diametre = diametre;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.marque</code>.
     */
    public String getMarque() {
        return this.marque;
    }

    /**
     * Setter for <code>edp.pull_hydrant.marque</code>.
     */
    public PullHydrant setMarque(String marque) {
        this.marque = marque;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.modele</code>.
     */
    public String getModele() {
        return this.modele;
    }

    /**
     * Setter for <code>edp.pull_hydrant.modele</code>.
     */
    public PullHydrant setModele(String modele) {
        this.modele = modele;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.diametre_canalisation</code>.
     */
    public Integer getDiametreCanalisation() {
        return this.diametreCanalisation;
    }

    /**
     * Setter for <code>edp.pull_hydrant.diametre_canalisation</code>.
     */
    public PullHydrant setDiametreCanalisation(Integer diametreCanalisation) {
        this.diametreCanalisation = diametreCanalisation;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.annee_fabrication</code>.
     */
    public String getAnneeFabrication() {
        return this.anneeFabrication;
    }

    /**
     * Setter for <code>edp.pull_hydrant.annee_fabrication</code>.
     */
    public PullHydrant setAnneeFabrication(String anneeFabrication) {
        this.anneeFabrication = anneeFabrication;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.dispo_terrestre</code>.
     */
    public String getDispoTerrestre() {
        return this.dispoTerrestre;
    }

    /**
     * Setter for <code>edp.pull_hydrant.dispo_terrestre</code>.
     */
    public PullHydrant setDispoTerrestre(String dispoTerrestre) {
        this.dispoTerrestre = dispoTerrestre;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.dispo_hbe</code>.
     */
    public String getDispoHbe() {
        return this.dispoHbe;
    }

    /**
     * Setter for <code>edp.pull_hydrant.dispo_hbe</code>.
     */
    public PullHydrant setDispoHbe(String dispoHbe) {
        this.dispoHbe = dispoHbe;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.numero_voie</code>.
     */
    public Integer getNumeroVoie() {
        return this.numeroVoie;
    }

    /**
     * Setter for <code>edp.pull_hydrant.numero_voie</code>.
     */
    public PullHydrant setNumeroVoie(Integer numeroVoie) {
        this.numeroVoie = numeroVoie;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.suffixe_voie</code>.
     */
    public String getSuffixeVoie() {
        return this.suffixeVoie;
    }

    /**
     * Setter for <code>edp.pull_hydrant.suffixe_voie</code>.
     */
    public PullHydrant setSuffixeVoie(String suffixeVoie) {
        this.suffixeVoie = suffixeVoie;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.niveau</code>.
     */
    public String getNiveau() {
        return this.niveau;
    }

    /**
     * Setter for <code>edp.pull_hydrant.niveau</code>.
     */
    public PullHydrant setNiveau(String niveau) {
        this.niveau = niveau;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.voie</code>.
     */
    public String getVoie() {
        return this.voie;
    }

    /**
     * Setter for <code>edp.pull_hydrant.voie</code>.
     */
    public PullHydrant setVoie(String voie) {
        this.voie = voie;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.voie2</code>.
     */
    public String getVoie2() {
        return this.voie2;
    }

    /**
     * Setter for <code>edp.pull_hydrant.voie2</code>.
     */
    public PullHydrant setVoie2(String voie2) {
        this.voie2 = voie2;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.complement</code>.
     */
    public String getComplement() {
        return this.complement;
    }

    /**
     * Setter for <code>edp.pull_hydrant.complement</code>.
     */
    public PullHydrant setComplement(String complement) {
        this.complement = complement;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.en_face</code>.
     */
    public Boolean getEnFace() {
        return this.enFace;
    }

    /**
     * Setter for <code>edp.pull_hydrant.en_face</code>.
     */
    public PullHydrant setEnFace(Boolean enFace) {
        this.enFace = enFace;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.commune</code>.
     */
    public String getCommune() {
        return this.commune;
    }

    /**
     * Setter for <code>edp.pull_hydrant.commune</code>.
     */
    public PullHydrant setCommune(String commune) {
        this.commune = commune;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.domaine</code>.
     */
    public String getDomaine() {
        return this.domaine;
    }

    /**
     * Setter for <code>edp.pull_hydrant.domaine</code>.
     */
    public PullHydrant setDomaine(String domaine) {
        this.domaine = domaine;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.nature</code>.
     */
    public String getNature() {
        return this.nature;
    }

    /**
     * Setter for <code>edp.pull_hydrant.nature</code>.
     */
    public PullHydrant setNature(String nature) {
        this.nature = nature;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.nature_deci</code>.
     */
    public String getNatureDeci() {
        return this.natureDeci;
    }

    /**
     * Setter for <code>edp.pull_hydrant.nature_deci</code>.
     */
    public PullHydrant setNatureDeci(String natureDeci) {
        this.natureDeci = natureDeci;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant.indispo_temporaire</code>.
     */
    public Boolean getIndispoTemporaire() {
        return this.indispoTemporaire;
    }

    /**
     * Setter for <code>edp.pull_hydrant.indispo_temporaire</code>.
     */
    public PullHydrant setIndispoTemporaire(Boolean indispoTemporaire) {
        this.indispoTemporaire = indispoTemporaire;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PullHydrant (");

        sb.append(id);
        sb.append(", ").append(numero);
        sb.append(", ").append(dateModification);
        sb.append(", ").append(auteurModification);
        sb.append(", ").append(diametre);
        sb.append(", ").append(marque);
        sb.append(", ").append(modele);
        sb.append(", ").append(diametreCanalisation);
        sb.append(", ").append(anneeFabrication);
        sb.append(", ").append(dispoTerrestre);
        sb.append(", ").append(dispoHbe);
        sb.append(", ").append(numeroVoie);
        sb.append(", ").append(suffixeVoie);
        sb.append(", ").append(niveau);
        sb.append(", ").append(voie);
        sb.append(", ").append(voie2);
        sb.append(", ").append(complement);
        sb.append(", ").append(enFace);
        sb.append(", ").append(commune);
        sb.append(", ").append(domaine);
        sb.append(", ").append(nature);
        sb.append(", ").append(natureDeci);
        sb.append(", ").append(indispoTemporaire);

        sb.append(")");
        return sb.toString();
    }
}
