/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PullMessage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private LocalDateTime date;
    private LocalDateTime dateModification;
    private String        operation;
    private String        type;
    private String        hydrant;

    public PullMessage() {}

    public PullMessage(PullMessage value) {
        this.id = value.id;
        this.date = value.date;
        this.dateModification = value.dateModification;
        this.operation = value.operation;
        this.type = value.type;
        this.hydrant = value.hydrant;
    }

    public PullMessage(
        Integer       id,
        LocalDateTime date,
        LocalDateTime dateModification,
        String        operation,
        String        type,
        String        hydrant
    ) {
        this.id = id;
        this.date = date;
        this.dateModification = dateModification;
        this.operation = operation;
        this.type = type;
        this.hydrant = hydrant;
    }

    /**
     * Getter for <code>edp.pull_message.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>edp.pull_message.id</code>.
     */
    public PullMessage setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>edp.pull_message.date</code>.
     */
    public LocalDateTime getDate() {
        return this.date;
    }

    /**
     * Setter for <code>edp.pull_message.date</code>.
     */
    public PullMessage setDate(LocalDateTime date) {
        this.date = date;
        return this;
    }

    /**
     * Getter for <code>edp.pull_message.date_modification</code>.
     */
    public LocalDateTime getDateModification() {
        return this.dateModification;
    }

    /**
     * Setter for <code>edp.pull_message.date_modification</code>.
     */
    public PullMessage setDateModification(LocalDateTime dateModification) {
        this.dateModification = dateModification;
        return this;
    }

    /**
     * Getter for <code>edp.pull_message.operation</code>.
     */
    public String getOperation() {
        return this.operation;
    }

    /**
     * Setter for <code>edp.pull_message.operation</code>.
     */
    public PullMessage setOperation(String operation) {
        this.operation = operation;
        return this;
    }

    /**
     * Getter for <code>edp.pull_message.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>edp.pull_message.type</code>.
     */
    public PullMessage setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>edp.pull_message.hydrant</code>.
     */
    public String getHydrant() {
        return this.hydrant;
    }

    /**
     * Setter for <code>edp.pull_message.hydrant</code>.
     */
    public PullMessage setHydrant(String hydrant) {
        this.hydrant = hydrant;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PullMessage (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(dateModification);
        sb.append(", ").append(operation);
        sb.append(", ").append(type);
        sb.append(", ").append(hydrant);

        sb.append(")");
        return sb.toString();
    }
}
