/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PullHydrantVisite implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Long          hydrant;
    private LocalDateTime date;
    private String        type;
    private Boolean       ctrlDebitPression;
    private String        agent1;
    private String        agent2;
    private Integer       debit;
    private Integer       debitMax;
    private Double        pression;
    private Double        pressionDyn;
    private Double        pressionDynDeb;
    private String        observations;

    public PullHydrantVisite() {}

    public PullHydrantVisite(PullHydrantVisite value) {
        this.id = value.id;
        this.hydrant = value.hydrant;
        this.date = value.date;
        this.type = value.type;
        this.ctrlDebitPression = value.ctrlDebitPression;
        this.agent1 = value.agent1;
        this.agent2 = value.agent2;
        this.debit = value.debit;
        this.debitMax = value.debitMax;
        this.pression = value.pression;
        this.pressionDyn = value.pressionDyn;
        this.pressionDynDeb = value.pressionDynDeb;
        this.observations = value.observations;
    }

    public PullHydrantVisite(
        Integer       id,
        Long          hydrant,
        LocalDateTime date,
        String        type,
        Boolean       ctrlDebitPression,
        String        agent1,
        String        agent2,
        Integer       debit,
        Integer       debitMax,
        Double        pression,
        Double        pressionDyn,
        Double        pressionDynDeb,
        String        observations
    ) {
        this.id = id;
        this.hydrant = hydrant;
        this.date = date;
        this.type = type;
        this.ctrlDebitPression = ctrlDebitPression;
        this.agent1 = agent1;
        this.agent2 = agent2;
        this.debit = debit;
        this.debitMax = debitMax;
        this.pression = pression;
        this.pressionDyn = pressionDyn;
        this.pressionDynDeb = pressionDynDeb;
        this.observations = observations;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.id</code>.
     */
    public PullHydrantVisite setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.hydrant</code>.
     */
    public Long getHydrant() {
        return this.hydrant;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.hydrant</code>.
     */
    public PullHydrantVisite setHydrant(Long hydrant) {
        this.hydrant = hydrant;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.date</code>.
     */
    public LocalDateTime getDate() {
        return this.date;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.date</code>.
     */
    public PullHydrantVisite setDate(LocalDateTime date) {
        this.date = date;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.type</code>.
     */
    public PullHydrantVisite setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.ctrl_debit_pression</code>.
     */
    public Boolean getCtrlDebitPression() {
        return this.ctrlDebitPression;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.ctrl_debit_pression</code>.
     */
    public PullHydrantVisite setCtrlDebitPression(Boolean ctrlDebitPression) {
        this.ctrlDebitPression = ctrlDebitPression;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.agent1</code>.
     */
    public String getAgent1() {
        return this.agent1;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.agent1</code>.
     */
    public PullHydrantVisite setAgent1(String agent1) {
        this.agent1 = agent1;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.agent2</code>.
     */
    public String getAgent2() {
        return this.agent2;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.agent2</code>.
     */
    public PullHydrantVisite setAgent2(String agent2) {
        this.agent2 = agent2;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.debit</code>.
     */
    public Integer getDebit() {
        return this.debit;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.debit</code>.
     */
    public PullHydrantVisite setDebit(Integer debit) {
        this.debit = debit;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.debit_max</code>.
     */
    public Integer getDebitMax() {
        return this.debitMax;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.debit_max</code>.
     */
    public PullHydrantVisite setDebitMax(Integer debitMax) {
        this.debitMax = debitMax;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.pression</code>.
     */
    public Double getPression() {
        return this.pression;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.pression</code>.
     */
    public PullHydrantVisite setPression(Double pression) {
        this.pression = pression;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.pression_dyn</code>.
     */
    public Double getPressionDyn() {
        return this.pressionDyn;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.pression_dyn</code>.
     */
    public PullHydrantVisite setPressionDyn(Double pressionDyn) {
        this.pressionDyn = pressionDyn;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.pression_dyn_deb</code>.
     */
    public Double getPressionDynDeb() {
        return this.pressionDynDeb;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.pression_dyn_deb</code>.
     */
    public PullHydrantVisite setPressionDynDeb(Double pressionDynDeb) {
        this.pressionDynDeb = pressionDynDeb;
        return this;
    }

    /**
     * Getter for <code>edp.pull_hydrant_visite.observations</code>.
     */
    public String getObservations() {
        return this.observations;
    }

    /**
     * Setter for <code>edp.pull_hydrant_visite.observations</code>.
     */
    public PullHydrantVisite setObservations(String observations) {
        this.observations = observations;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PullHydrantVisite (");

        sb.append(id);
        sb.append(", ").append(hydrant);
        sb.append(", ").append(date);
        sb.append(", ").append(type);
        sb.append(", ").append(ctrlDebitPression);
        sb.append(", ").append(agent1);
        sb.append(", ").append(agent2);
        sb.append(", ").append(debit);
        sb.append(", ").append(debitMax);
        sb.append(", ").append(pression);
        sb.append(", ").append(pressionDyn);
        sb.append(", ").append(pressionDynDeb);
        sb.append(", ").append(observations);

        sb.append(")");
        return sb.toString();
    }
}
