/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.locationtech.jts.geom.Point;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TracabilitePei implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        reference;
    private Point         geometry1;
    private String        typeObjet;
    private Integer       prive;
    private String        precisionPeiPrive;
    private String        adresse;
    private String        notesLocalisation;
    private Integer       diametre;
    private String        modele;
    private String        diametreCanalisation;
    private String        etat;
    private LocalDateTime dateMajP;
    private LocalDateTime dateMajE;
    private LocalDateTime dateTraca;
    private LocalDateTime dateEssai;
    private BigDecimal    essaiPressionStatique;
    private BigDecimal    essaiPressionDynamique;
    private BigDecimal    essaiDebit;
    private LocalDateTime dateMajQp;
    private LocalDateTime dateDerniereVisite;
    private String        typeDerniereVisite;
    private LocalDateTime dateMajCf;
    private LocalDateTime dateMajNp;
    private LocalDateTime dateMajMj;

    public TracabilitePei() {}

    public TracabilitePei(TracabilitePei value) {
        this.id = value.id;
        this.reference = value.reference;
        this.geometry1 = value.geometry1;
        this.typeObjet = value.typeObjet;
        this.prive = value.prive;
        this.precisionPeiPrive = value.precisionPeiPrive;
        this.adresse = value.adresse;
        this.notesLocalisation = value.notesLocalisation;
        this.diametre = value.diametre;
        this.modele = value.modele;
        this.diametreCanalisation = value.diametreCanalisation;
        this.etat = value.etat;
        this.dateMajP = value.dateMajP;
        this.dateMajE = value.dateMajE;
        this.dateTraca = value.dateTraca;
        this.dateEssai = value.dateEssai;
        this.essaiPressionStatique = value.essaiPressionStatique;
        this.essaiPressionDynamique = value.essaiPressionDynamique;
        this.essaiDebit = value.essaiDebit;
        this.dateMajQp = value.dateMajQp;
        this.dateDerniereVisite = value.dateDerniereVisite;
        this.typeDerniereVisite = value.typeDerniereVisite;
        this.dateMajCf = value.dateMajCf;
        this.dateMajNp = value.dateMajNp;
        this.dateMajMj = value.dateMajMj;
    }

    public TracabilitePei(
        Integer       id,
        String        reference,
        Point         geometry1,
        String        typeObjet,
        Integer       prive,
        String        precisionPeiPrive,
        String        adresse,
        String        notesLocalisation,
        Integer       diametre,
        String        modele,
        String        diametreCanalisation,
        String        etat,
        LocalDateTime dateMajP,
        LocalDateTime dateMajE,
        LocalDateTime dateTraca,
        LocalDateTime dateEssai,
        BigDecimal    essaiPressionStatique,
        BigDecimal    essaiPressionDynamique,
        BigDecimal    essaiDebit,
        LocalDateTime dateMajQp,
        LocalDateTime dateDerniereVisite,
        String        typeDerniereVisite,
        LocalDateTime dateMajCf,
        LocalDateTime dateMajNp,
        LocalDateTime dateMajMj
    ) {
        this.id = id;
        this.reference = reference;
        this.geometry1 = geometry1;
        this.typeObjet = typeObjet;
        this.prive = prive;
        this.precisionPeiPrive = precisionPeiPrive;
        this.adresse = adresse;
        this.notesLocalisation = notesLocalisation;
        this.diametre = diametre;
        this.modele = modele;
        this.diametreCanalisation = diametreCanalisation;
        this.etat = etat;
        this.dateMajP = dateMajP;
        this.dateMajE = dateMajE;
        this.dateTraca = dateTraca;
        this.dateEssai = dateEssai;
        this.essaiPressionStatique = essaiPressionStatique;
        this.essaiPressionDynamique = essaiPressionDynamique;
        this.essaiDebit = essaiDebit;
        this.dateMajQp = dateMajQp;
        this.dateDerniereVisite = dateDerniereVisite;
        this.typeDerniereVisite = typeDerniereVisite;
        this.dateMajCf = dateMajCf;
        this.dateMajNp = dateMajNp;
        this.dateMajMj = dateMajMj;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.id</code>.
     */
    public TracabilitePei setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.reference</code>.
     */
    public String getReference() {
        return this.reference;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.reference</code>.
     */
    public TracabilitePei setReference(String reference) {
        this.reference = reference;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.geometry1</code>.
     */
    public Point getGeometry1() {
        return this.geometry1;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.geometry1</code>.
     */
    public TracabilitePei setGeometry1(Point geometry1) {
        this.geometry1 = geometry1;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.type_objet</code>.
     */
    public String getTypeObjet() {
        return this.typeObjet;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.type_objet</code>.
     */
    public TracabilitePei setTypeObjet(String typeObjet) {
        this.typeObjet = typeObjet;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.prive</code>.
     */
    public Integer getPrive() {
        return this.prive;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.prive</code>.
     */
    public TracabilitePei setPrive(Integer prive) {
        this.prive = prive;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.precision_pei_prive</code>.
     */
    public String getPrecisionPeiPrive() {
        return this.precisionPeiPrive;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.precision_pei_prive</code>.
     */
    public TracabilitePei setPrecisionPeiPrive(String precisionPeiPrive) {
        this.precisionPeiPrive = precisionPeiPrive;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.adresse</code>.
     */
    public String getAdresse() {
        return this.adresse;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.adresse</code>.
     */
    public TracabilitePei setAdresse(String adresse) {
        this.adresse = adresse;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.notes_localisation</code>.
     */
    public String getNotesLocalisation() {
        return this.notesLocalisation;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.notes_localisation</code>.
     */
    public TracabilitePei setNotesLocalisation(String notesLocalisation) {
        this.notesLocalisation = notesLocalisation;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.diametre</code>.
     */
    public Integer getDiametre() {
        return this.diametre;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.diametre</code>.
     */
    public TracabilitePei setDiametre(Integer diametre) {
        this.diametre = diametre;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.modele</code>.
     */
    public String getModele() {
        return this.modele;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.modele</code>.
     */
    public TracabilitePei setModele(String modele) {
        this.modele = modele;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.diametre_canalisation</code>.
     */
    public String getDiametreCanalisation() {
        return this.diametreCanalisation;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.diametre_canalisation</code>.
     */
    public TracabilitePei setDiametreCanalisation(String diametreCanalisation) {
        this.diametreCanalisation = diametreCanalisation;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.etat</code>.
     */
    public String getEtat() {
        return this.etat;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.etat</code>.
     */
    public TracabilitePei setEtat(String etat) {
        this.etat = etat;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_maj_p</code>.
     */
    public LocalDateTime getDateMajP() {
        return this.dateMajP;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_maj_p</code>.
     */
    public TracabilitePei setDateMajP(LocalDateTime dateMajP) {
        this.dateMajP = dateMajP;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_maj_e</code>.
     */
    public LocalDateTime getDateMajE() {
        return this.dateMajE;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_maj_e</code>.
     */
    public TracabilitePei setDateMajE(LocalDateTime dateMajE) {
        this.dateMajE = dateMajE;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_traca</code>.
     */
    public LocalDateTime getDateTraca() {
        return this.dateTraca;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_traca</code>.
     */
    public TracabilitePei setDateTraca(LocalDateTime dateTraca) {
        this.dateTraca = dateTraca;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_essai</code>.
     */
    public LocalDateTime getDateEssai() {
        return this.dateEssai;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_essai</code>.
     */
    public TracabilitePei setDateEssai(LocalDateTime dateEssai) {
        this.dateEssai = dateEssai;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.essai_pression_statique</code>.
     */
    public BigDecimal getEssaiPressionStatique() {
        return this.essaiPressionStatique;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.essai_pression_statique</code>.
     */
    public TracabilitePei setEssaiPressionStatique(BigDecimal essaiPressionStatique) {
        this.essaiPressionStatique = essaiPressionStatique;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.essai_pression_dynamique</code>.
     */
    public BigDecimal getEssaiPressionDynamique() {
        return this.essaiPressionDynamique;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.essai_pression_dynamique</code>.
     */
    public TracabilitePei setEssaiPressionDynamique(BigDecimal essaiPressionDynamique) {
        this.essaiPressionDynamique = essaiPressionDynamique;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.essai_debit</code>.
     */
    public BigDecimal getEssaiDebit() {
        return this.essaiDebit;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.essai_debit</code>.
     */
    public TracabilitePei setEssaiDebit(BigDecimal essaiDebit) {
        this.essaiDebit = essaiDebit;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_maj_qp</code>.
     */
    public LocalDateTime getDateMajQp() {
        return this.dateMajQp;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_maj_qp</code>.
     */
    public TracabilitePei setDateMajQp(LocalDateTime dateMajQp) {
        this.dateMajQp = dateMajQp;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_derniere_visite</code>.
     */
    public LocalDateTime getDateDerniereVisite() {
        return this.dateDerniereVisite;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_derniere_visite</code>.
     */
    public TracabilitePei setDateDerniereVisite(LocalDateTime dateDerniereVisite) {
        this.dateDerniereVisite = dateDerniereVisite;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.type_derniere_visite</code>.
     */
    public String getTypeDerniereVisite() {
        return this.typeDerniereVisite;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.type_derniere_visite</code>.
     */
    public TracabilitePei setTypeDerniereVisite(String typeDerniereVisite) {
        this.typeDerniereVisite = typeDerniereVisite;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_maj_cf</code>.
     */
    public LocalDateTime getDateMajCf() {
        return this.dateMajCf;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_maj_cf</code>.
     */
    public TracabilitePei setDateMajCf(LocalDateTime dateMajCf) {
        this.dateMajCf = dateMajCf;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_maj_np</code>.
     */
    public LocalDateTime getDateMajNp() {
        return this.dateMajNp;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_maj_np</code>.
     */
    public TracabilitePei setDateMajNp(LocalDateTime dateMajNp) {
        this.dateMajNp = dateMajNp;
        return this;
    }

    /**
     * Getter for <code>edp.tracabilite_pei.date_maj_mj</code>.
     */
    public LocalDateTime getDateMajMj() {
        return this.dateMajMj;
    }

    /**
     * Setter for <code>edp.tracabilite_pei.date_maj_mj</code>.
     */
    public TracabilitePei setDateMajMj(LocalDateTime dateMajMj) {
        this.dateMajMj = dateMajMj;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TracabilitePei (");

        sb.append(id);
        sb.append(", ").append(reference);
        sb.append(", ").append(geometry1);
        sb.append(", ").append(typeObjet);
        sb.append(", ").append(prive);
        sb.append(", ").append(precisionPeiPrive);
        sb.append(", ").append(adresse);
        sb.append(", ").append(notesLocalisation);
        sb.append(", ").append(diametre);
        sb.append(", ").append(modele);
        sb.append(", ").append(diametreCanalisation);
        sb.append(", ").append(etat);
        sb.append(", ").append(dateMajP);
        sb.append(", ").append(dateMajE);
        sb.append(", ").append(dateTraca);
        sb.append(", ").append(dateEssai);
        sb.append(", ").append(essaiPressionStatique);
        sb.append(", ").append(essaiPressionDynamique);
        sb.append(", ").append(essaiDebit);
        sb.append(", ").append(dateMajQp);
        sb.append(", ").append(dateDerniereVisite);
        sb.append(", ").append(typeDerniereVisite);
        sb.append(", ").append(dateMajCf);
        sb.append(", ").append(dateMajNp);
        sb.append(", ").append(dateMajMj);

        sb.append(")");
        return sb.toString();
    }
}
