/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VueErreursEdp implements Serializable {

    private static final long serialVersionUID = 1L;

    private LocalDateTime date;
    private Boolean       notifie;
    private String        messageErreur;
    private String        messageAction;
    private String        contexte;
    private String        type;
    private String        reference;
    private String        json;

    public VueErreursEdp() {}

    public VueErreursEdp(VueErreursEdp value) {
        this.date = value.date;
        this.notifie = value.notifie;
        this.messageErreur = value.messageErreur;
        this.messageAction = value.messageAction;
        this.contexte = value.contexte;
        this.type = value.type;
        this.reference = value.reference;
        this.json = value.json;
    }

    public VueErreursEdp(
        LocalDateTime date,
        Boolean       notifie,
        String        messageErreur,
        String        messageAction,
        String        contexte,
        String        type,
        String        reference,
        String        json
    ) {
        this.date = date;
        this.notifie = notifie;
        this.messageErreur = messageErreur;
        this.messageAction = messageAction;
        this.contexte = contexte;
        this.type = type;
        this.reference = reference;
        this.json = json;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.date</code>.
     */
    public LocalDateTime getDate() {
        return this.date;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.date</code>.
     */
    public VueErreursEdp setDate(LocalDateTime date) {
        this.date = date;
        return this;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.notifie</code>.
     */
    public Boolean getNotifie() {
        return this.notifie;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.notifie</code>.
     */
    public VueErreursEdp setNotifie(Boolean notifie) {
        this.notifie = notifie;
        return this;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.message_erreur</code>.
     */
    public String getMessageErreur() {
        return this.messageErreur;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.message_erreur</code>.
     */
    public VueErreursEdp setMessageErreur(String messageErreur) {
        this.messageErreur = messageErreur;
        return this;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.message_action</code>.
     */
    public String getMessageAction() {
        return this.messageAction;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.message_action</code>.
     */
    public VueErreursEdp setMessageAction(String messageAction) {
        this.messageAction = messageAction;
        return this;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.contexte</code>.
     */
    public String getContexte() {
        return this.contexte;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.contexte</code>.
     */
    public VueErreursEdp setContexte(String contexte) {
        this.contexte = contexte;
        return this;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.type</code>.
     */
    public VueErreursEdp setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.reference</code>.
     */
    public String getReference() {
        return this.reference;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.reference</code>.
     */
    public VueErreursEdp setReference(String reference) {
        this.reference = reference;
        return this;
    }

    /**
     * Getter for <code>edp.vue_erreurs_edp.json</code>.
     */
    public String getJson() {
        return this.json;
    }

    /**
     * Setter for <code>edp.vue_erreurs_edp.json</code>.
     */
    public VueErreursEdp setJson(String json) {
        this.json = json;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VueErreursEdp (");

        sb.append(date);
        sb.append(", ").append(notifie);
        sb.append(", ").append(messageErreur);
        sb.append(", ").append(messageAction);
        sb.append(", ").append(contexte);
        sb.append(", ").append(type);
        sb.append(", ").append(reference);
        sb.append(", ").append(json);

        sb.append(")");
        return sb.toString();
    }
}
