/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.tables.pojos;

import java.io.Serializable;
import org.jooq.XML;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VueErreurToNotify implements Serializable {

  private static final long serialVersionUID = 1L;

  private String contexte;
  private Long erreursNombre;
  private String erreursIds;
  private XML xmlNotification;

  public VueErreurToNotify() {}

  public VueErreurToNotify(VueErreurToNotify value) {
    this.contexte = value.contexte;
    this.erreursNombre = value.erreursNombre;
    this.erreursIds = value.erreursIds;
    this.xmlNotification = value.xmlNotification;
  }

  public VueErreurToNotify(
      String contexte, Long erreursNombre, String erreursIds, XML xmlNotification) {
    this.contexte = contexte;
    this.erreursNombre = erreursNombre;
    this.erreursIds = erreursIds;
    this.xmlNotification = xmlNotification;
  }

  /** Getter for <code>edp.vue_erreur_to_notify.contexte</code>. */
  public String getContexte() {
    return this.contexte;
  }

  /** Setter for <code>edp.vue_erreur_to_notify.contexte</code>. */
  public VueErreurToNotify setContexte(String contexte) {
    this.contexte = contexte;
    return this;
  }

  /** Getter for <code>edp.vue_erreur_to_notify.erreurs_nombre</code>. */
  public Long getErreursNombre() {
    return this.erreursNombre;
  }

  /** Setter for <code>edp.vue_erreur_to_notify.erreurs_nombre</code>. */
  public VueErreurToNotify setErreursNombre(Long erreursNombre) {
    this.erreursNombre = erreursNombre;
    return this;
  }

  /** Getter for <code>edp.vue_erreur_to_notify.erreurs_ids</code>. */
  public String getErreursIds() {
    return this.erreursIds;
  }

  /** Setter for <code>edp.vue_erreur_to_notify.erreurs_ids</code>. */
  public VueErreurToNotify setErreursIds(String erreursIds) {
    this.erreursIds = erreursIds;
    return this;
  }

  /** Getter for <code>edp.vue_erreur_to_notify.xml_notification</code>. */
  public XML getXmlNotification() {
    return this.xmlNotification;
  }

  /** Setter for <code>edp.vue_erreur_to_notify.xml_notification</code>. */
  public VueErreurToNotify setXmlNotification(XML xmlNotification) {
    this.xmlNotification = xmlNotification;
    return this;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("VueErreurToNotify (");

    sb.append(contexte);
    sb.append(", ").append(erreursNombre);
    sb.append(", ").append(erreursIds);
    sb.append(", ").append(xmlNotification);

    sb.append(")");
    return sb.toString();
  }
}
