/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.routines;

import fr.eaudeparis.syncremocra.db.model.Edp;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Changedatacapture extends AbstractRoutine<Integer> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>edp.changedatacapture.RETURN_VALUE</code>. */
  public static final Parameter<Integer> RETURN_VALUE =
      Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

  /** Create a new routine call instance */
  public Changedatacapture() {
    super("changedatacapture", Edp.EDP, SQLDataType.INTEGER);

    setReturnParameter(RETURN_VALUE);
  }
}
