/*
 * This file is generated by jOOQ.
 */
package fr.eaudeparis.syncremocra.db.model.routines;


import fr.eaudeparis.syncremocra.db.model.Edp;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraiterSpecifique extends AbstractRoutine<LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>edp.traiter_specifique.RETURN_VALUE</code>.
     */
    public static final Parameter<LocalDateTime> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.LOCALDATETIME(0), false, false);

    /**
     * The parameter <code>edp.traiter_specifique.datelaplusrecente</code>.
     */
    public static final Parameter<LocalDateTime> DATELAPLUSRECENTE = Internal.createParameter("datelaplusrecente", SQLDataType.LOCALDATETIME(0), false, false);

    /**
     * The parameter <code>edp.traiter_specifique.derniereremontee</code>.
     */
    public static final Parameter<LocalDateTime> DERNIEREREMONTEE = Internal.createParameter("derniereremontee", SQLDataType.LOCALDATETIME(0), false, false);

    /**
     * The parameter <code>edp.traiter_specifique.current_execution</code>.
     */
    public static final Parameter<LocalDateTime> CURRENT_EXECUTION = Internal.createParameter("current_execution", SQLDataType.LOCALDATETIME(0), false, false);

    /**
     * The parameter <code>edp.traiter_specifique.param_reference</code>.
     */
    public static final Parameter<String> PARAM_REFERENCE = Internal.createParameter("param_reference", SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>edp.traiter_specifique.param_type</code>.
     */
    public static final Parameter<String> PARAM_TYPE = Internal.createParameter("param_type", SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public TraiterSpecifique() {
        super("traiter_specifique", Edp.EDP, SQLDataType.LOCALDATETIME(0));

        setReturnParameter(RETURN_VALUE);
        addInParameter(DATELAPLUSRECENTE);
        addInParameter(DERNIEREREMONTEE);
        addInParameter(CURRENT_EXECUTION);
        addInParameter(PARAM_REFERENCE);
        addInParameter(PARAM_TYPE);
    }

    /**
     * Set the <code>datelaplusrecente</code> parameter IN value to the routine
     */
    public void setDatelaplusrecente(LocalDateTime value) {
        setValue(DATELAPLUSRECENTE, value);
    }

    /**
     * Set the <code>datelaplusrecente</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TraiterSpecifique setDatelaplusrecente(Field<LocalDateTime> field) {
        setField(DATELAPLUSRECENTE, field);
        return this;
    }

    /**
     * Set the <code>derniereremontee</code> parameter IN value to the routine
     */
    public void setDerniereremontee(LocalDateTime value) {
        setValue(DERNIEREREMONTEE, value);
    }

    /**
     * Set the <code>derniereremontee</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TraiterSpecifique setDerniereremontee(Field<LocalDateTime> field) {
        setField(DERNIEREREMONTEE, field);
        return this;
    }

    /**
     * Set the <code>current_execution</code> parameter IN value to the routine
     */
    public void setCurrentExecution(LocalDateTime value) {
        setValue(CURRENT_EXECUTION, value);
    }

    /**
     * Set the <code>current_execution</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TraiterSpecifique setCurrentExecution(Field<LocalDateTime> field) {
        setField(CURRENT_EXECUTION, field);
        return this;
    }

    /**
     * Set the <code>param_reference</code> parameter IN value to the routine
     */
    public void setParamReference(String value) {
        setValue(PARAM_REFERENCE, value);
    }

    /**
     * Set the <code>param_reference</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TraiterSpecifique setParamReference(Field<String> field) {
        setField(PARAM_REFERENCE, field);
        return this;
    }

    /**
     * Set the <code>param_type</code> parameter IN value to the routine
     */
    public void setParamType(String value) {
        setValue(PARAM_TYPE, value);
    }

    /**
     * Set the <code>param_type</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public TraiterSpecifique setParamType(Field<String> field) {
        setField(PARAM_TYPE, field);
        return this;
    }
}
