CREATE TABLE edp.referentiel_anomalies (
    code_BSPP CHARACTER VARYING NOT NULL,
    code_EDP CHARACTER VARYING NOT NULL,
    PRIMARY KEY(code_BSPP, code_EDP)
);
ALTER TABLE edp.referentiel_anomalies OWNER TO edp;

INSERT INTO edp.referentiel_anomalies(code_BSPP, code_EDP) VALUES
('BSPP_APEN', 'INACCESSIBLE'),
('BSPP_APEN', 'APP SUR CHANTIER'),
('BSPP_APSE', 'APP SANS EAU'),
('BSPP_PUIS', 'PUISAGE'),
('BSPP_SINC', 'APP SIGNALE'),
('APAREN', 'APP A RENOUVELER'),
('APAREP', 'APP A REPARER'),
('FERMHIV', 'FERMETURE HIVERNALE'),
('FERMDEMTI', 'FERMETURE DEMANDE TIERS'),
('SSCOND', 'SANS CONDUITE'),
('ARREAU', 'ARRET EAU'),
('STRTPOOL', 'STREETPOOLING');