DELETE FROM edp.type_erreur;

INSERT INTO edp.type_erreur(code, iterations, contexte, message_action) VALUES
('0001', 10, 'EDP_SYSTEME', 'Vérifier que le serveur est opérationnel et vérifier le paramétrage selon le processus défini dans le manuel de paramétrage'),
('0002', 10, 'EDP_SYSTEME', 'Vérifier que le serveur est opérationnel et vérifier le paramétrage selon le processus défini dans le manuel de paramétrage'),
('0003', 10, 'EDP_SYSTEME', 'Vérifier que le serveur est opérationnel (demande Atol CD) et que son accès est autorisé (firewall EDP, etc.)'),
('1000', 1, 'EDP_METIER', 'Supprimer le PEI dans la base EDP (WatGIS)'),
('1300', 1, 'REMOCRA_METIER', 'Procéder à l''attribution des droits via l''interface applicative REMOCRA'),
('1001', 1, 'EDP_METIER', 'Mettre à jour la table de correspondance au sein de la base de synchronisation EDP - REMOCRA et attendre la prochaine synchronisaton'),
('1002', 1, 'EDP_METIER', 'Mettre à jour la table de correspondance au sein de la base de synchronisation EDP - REMOCRA et attendre la prochaine synchronisaton'),
('1003', 1, 'EDP_METIER', 'Mettre à jour la table de correspondance au sein de la base de synchronisation EDP - REMOCRA et attendre la prochaine synchronisaton'),
('1004', 1, 'EDP_METIER', 'Mettre à jour la table de correspondance au sein de la base de synchronisation EDP - REMOCRA et attendre la prochaine synchronisaton'),
('1005', 1, 'EDP_METIER', 'Mettre à jour la table de correspondance au sein de la base de synchronisation EDP - REMOCRA et attendre la prochaine synchronisaton'),
('1301', 1, 'REMOCRA_SYSTEME', 'Procéder à l''analyse des logs applicatifs'),
('1006', 1, 'EDP_METIER', 'Mettre à jour la table de correspondance au sein de la base de synchronisation EDP - REMOCRA et attendre la prochaine synchronisaton'),
('1100', 1, 'REMOCRA_METIER', 'Procéder au rapprochement des deux PEI  via l''interface applicative REMOCRA'),
('1007', 1, 'REMOCRA_METIER', 'Supprimer le PEI dans WatGIS ou procéder à la création du PEI via l''interface applicative REMOCRA'),
('2000', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA et procéder à la vérification du formatage des dates '),
('2001', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA et procéder à la vérification du type de visite dans la base EDP'),
('2100', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA si nécessaire'),
('2101', 1, 'REMOCRA_METIER', 'S''assurer via l''interface applicative REMOCRA que le PEI dispose d''une visite de Réception'),
('2102', 1, 'REMOCRA_METIER', 'S''assurer via l''interface applicative REMOCRA que le PEI dispose d''une visite de Reconnaissance Opérationnelle Initiale'),
('2103', 1, 'EDP_METIER', 'Créer éventuellemet la visite via l''interface applicative REMOCRA en renseignant un autre type de visite'),
('2002', 1, 'EDP_METIER', 'Mettre à jour la table de correspondance au sein de la base de synchronisation EDP - REMOCRA'),
('2104', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA'),
('2105', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA et corriger éventuellement la valeur dans WatGIS'),
('2106', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA et corriger éventuellement la valeur dans WatGIS'),
('2107', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA et corriger éventuellement la valeur dans WatGIS'),
('2108', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA et corriger éventuellement la valeur dans WatGIS'),
('2109', 1, 'EDP_METIER', 'Créer la visite via l''interface applicative REMOCRA et corriger éventuellement la valeur dans WatGIS'),
('2300', 1, 'REMOCRA_SYSTEME', 'Faire procéder à l''analyse des logs applicatifs par le prestataire en charge de de l''hébergement de REMOCRA'),
('2003', 1, 'EDP_METIER', 'Aucune action'),
('0200', 1, 'EDP_SYSTEME', 'Vérifier le paramétrage de la clef d''API selon le processus défini dans le manuel de paramétrage et faire procéder, si nécessaire à l''attribution des droits via l''interface applicative REMOCRA'),
('2200', 1, 'EDP_METIER', 'Demander une évolution du dispositif'),
('2201', 1, 'EDP_METIER', 'Demander une évolution du dispositif'),
('2110', 1, 'EDP_METIER', 'Aucune action');