name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/app/Dockerfile --network=host --force-rm -t edp/syncremocra --build-arg APP_VERSION=1.0 --tag my-image-name:$(date +%s)

